import type { AUX_NS } from "./_namespaces";

let G = globalThis;

export const deprecated = G as never as never as AUX_NS["deprecated"];
export const js = G as never as never as AUX_NS["js"];
export const data = G as never as AUX_NS["data"];
export const streams = G as never as AUX_NS["streams"];
export const net = G as never as AUX_NS["net"];
export const storage = G as never as AUX_NS["storage"];
export const dom = G as never as AUX_NS["dom"];
export const html = G as never as AUX_NS["html"];
export const css = G as never as AUX_NS["css"];
export const svg = G as never as AUX_NS["svg"];
export const canvas = G as never as AUX_NS["canvas"];
export const webgl = G as never as AUX_NS["webgl"];
export const webgpu = G as never as AUX_NS["webgpu"];
export const audio = G as never as AUX_NS["audio"];
export const media = G as never as AUX_NS["media"];
export const rtc = G as never as AUX_NS["rtc"];
export const events = G as never as AUX_NS["events"];
export const input = G as never as AUX_NS["input"];
export const animation = G as never as AUX_NS["animation"];
export const performance = G as never as AUX_NS["performance"];
export const scheduling = G as never as AUX_NS["scheduling"];
export const workers = G as never as AUX_NS["workers"];
export const security = G as never as AUX_NS["security"];
export const nav = G as never as AUX_NS["nav"];
export const payment = G as never as AUX_NS["payment"];
export const ui = G as never as AUX_NS["ui"];
export const observers = G as never as AUX_NS["observers"];
