/**
 * Generated grouping of keys on `window` from:
 *   keyof (GLOBAL)
 *
 * Source package used for extraction:
 *   @types/web@0.0.352
 *   typescript@6.0.3
 *
 * Master split:
 * - `direct`: developer-facing entrypoints: functions, singleton objects, static namespaces,
 *   and constructors developers commonly call intentionally.
 * - `auxiliary`: browser/environment-created classes and objects. This is the hide/noise bucket
 *   for IDE discovery. When classification was doubtful, the key was moved here.
 *
 * Classification rule applied after semantic grouping:
 * - `Event`, `Error`, and PascalCase names ending in `Event` or `Error` are auxiliary.
 * - `dispatchEvent` and `reportError` remain direct because they are callable methods/functions,
 *   not event/error classes.
 * - `rtc.direct` intentionally contains only `RTCPeerConnection`; the rest of RTC is auxiliary.
 * - HTML/SVG/WebGL constructor names are auxiliary: create them through document/canvas APIs.
 */

type ECMAScriptNewerApis = "FinalizationRegistry" | "WeakRef" | "AggregateError"; // ES2020 is the baseline
type GLOBAL = Window & typeof globalThis & { [K in ECMAScriptNewerApis]: unknown };

export type MAIN_NS_KEY = keyof typeof mainWindowGroups;
export type MAIN_NS<NS extends MAIN_NS_KEY> = { [K in (typeof mainWindowGroups)[NS][number]]: GLOBAL[K] };
export type AUX_NS_KEY = keyof typeof auxiliaryWindowGroups;
export type AUX_NS<NS extends AUX_NS_KEY> = { [K in (typeof auxiliaryWindowGroups)[NS][number]]: GLOBAL[K] };

export type WindowKey = (keyof GLOBAL & string) | ECMAScriptNewerApis;

export type DereferenceKey<K extends string> = K extends keyof GLOBAL & string ? GLOBAL[K] : unknown;

export type WindowUsageKind = "main" | "auxiliary";

export type WindowGroupName =
  | "deprecated"
  | "js"
  | "data"
  | "streams"
  | "net"
  | "storage"
  | "dom"
  | "html"
  | "css"
  | "svg"
  | "canvas"
  | "webgl"
  | "webgpu"
  | "audio"
  | "media"
  | "rtc"
  | "events"
  | "input"
  | "animation"
  | "performance"
  | "scheduling"
  | "workers"
  | "security"
  | "nav"
  | "payment"
  | "ui"
  | "observers"
  | "rest";

export const windowUsageGroups = {
  main: {
    /** Deprecated or legacy browser globals. Direct entries are callable/readable but still not recommended. */
    // deprecated: [],
    /** ECMAScript language globals exposed through window/globalThis. */
    js: [
      "Array",
      "ArrayBuffer",
      "Atomics",
      "BigInt",
      "BigInt64Array",
      "BigUint64Array",
      "Boolean",
      "console",
      "DataView",
      "Date",
      "decodeURI",
      "decodeURIComponent",
      "encodeURI",
      "encodeURIComponent",
      "eval",
      "FinalizationRegistry",
      "Float32Array",
      "Float64Array",
      "Function",
      "globalThis",
      "Infinity",
      "Int16Array",
      "Int32Array",
      "Int8Array",
      "Intl",
      "isFinite",
      "isNaN",
      "JSON",
      "Map",
      "Math",
      "NaN",
      "Number",
      "Object",
      "parseFloat",
      "parseInt",
      "Promise",
      "Proxy",
      "Reflect",
      "RegExp",
      "Set",
      "SharedArrayBuffer",
      "String",
      "Symbol",
      "Uint16Array",
      "Uint32Array",
      "Uint8Array",
      "Uint8ClampedArray",
      "undefined",
      "WeakMap",
      "WeakRef",
      "WeakSet",
      "WebAssembly",
    ],
    /** Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers. */
    data: [
      "atob",
      "Blob",
      "btoa",
      "ByteLengthQueuingStrategy",
      "CompressionStream",
      "CountQueuingStrategy",
      "createImageBitmap",
      "DecompressionStream",
      "File",
      "FileReader",
      "FormData",
      "ImageData",
      "structuredClone",
      "TextDecoder",
      "TextDecoderStream",
      "TextEncoder",
      "TextEncoderStream",
      "URL",
      "URLPattern",
      "URLSearchParams",
    ],
    /** WHATWG stream primitives. */
    streams: ["ReadableStream", "TransformStream", "WritableStream"],
    /** Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging. */
    net: [
      "BroadcastChannel",
      "EventSource",
      "fetch",
      "Headers",
      "MessageChannel",
      "origin",
      "postMessage",
      "Request",
      "Response",
      "WebSocket",
      "WebTransport",
      "XMLHttpRequest",
    ],
    /** Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks. */
    storage: ["caches", "cookieStore", "IDBKeyRange", "indexedDB", "localStorage", "sessionStorage"],
    /** Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT. */
    dom: ["customElements", "document", "DOMParser", "Text", "XMLSerializer", "XPathEvaluator", "XSLTProcessor"],
    /** HTML element constructors and related HTML collections/factories. */
    // html: [],
    /** CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights. */
    css: ["getComputedStyle", "matchMedia"],
    /** SVG element constructors and SVG value/list helper objects. */
    // svg: [],
    /** 2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics. */
    // canvas: [],
    /** WebGL rendering contexts and WebGL resource/event constructors. */
    // webgl: [],
    /** WebGPU objects, constants, errors, resources, pipelines, queues, textures, and WGSL features. */
    // webgpu: [],
    /** Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers. */
    audio: [
      "AnalyserNode",
      "Audio",
      "AudioBuffer",
      "AudioBufferSourceNode",
      "AudioContext",
      "AudioWorkletNode",
      "BiquadFilterNode",
      "ChannelMergerNode",
      "ChannelSplitterNode",
      "ConstantSourceNode",
      "ConvolverNode",
      "DelayNode",
      "DynamicsCompressorNode",
      "GainNode",
      "IIRFilterNode",
      "MediaElementAudioSourceNode",
      "MediaStreamAudioDestinationNode",
      "MediaStreamAudioSourceNode",
      "OfflineAudioContext",
      "OscillatorNode",
      "PannerNode",
      "PeriodicWave",
      "StereoPannerNode",
      "WaveShaperNode",
    ],
    /** Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis. */
    media: [
      "documentPictureInPicture",
      "MediaRecorder",
      "MediaSource",
      "MediaStream",
      "speechSynthesis",
      "SpeechSynthesisUtterance",
    ],
    /** WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors. */
    rtc: ["RTCPeerConnection"],
    /** Global event handler slots plus general event constructors and event listener methods. */
    events: ["addEventListener", "dispatchEvent", "EventTarget", "removeEventListener"],
    /** Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input. */
    input: ["ClipboardItem", "DataTransfer", "getSelection"],
    /** Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF. */
    // animation: [],
    /** Performance timeline, observer, navigation/resource/paint/event timing, LCP. */
    performance: ["performance", "PerformanceObserver"],
    /** Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting. */
    scheduling: [
      "cancelAnimationFrame",
      "requestAnimationFrame",
      "cancelIdleCallback",
      "clearInterval",
      "clearTimeout",
      "queueMicrotask",
      "reportError",
      "requestIdleCallback",
      "scheduler",
      "setInterval",
      "setTimeout",
      "TaskController",
    ],
    /** Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals. */
    workers: ["Notification", "SharedWorker", "Worker"],
    /** Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event. */
    security: [
      "AbortController",
      "AbortSignal",
      "crossOriginIsolated",
      "crypto",
      "isSecureContext",
      "originAgentCluster",
      "PublicKeyCredential",
    ],
    /** Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint. */
    nav: ["navigator", "history", "location"],
    /** Payment Request API globals. */
    payment: ["PaymentRequest"],
    /** Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals. */
    ui: [
      "close",
      "devicePixelRatio",
      "innerHeight",
      "innerWidth",
      "open",
      "opener",
      "parent",
      "print",
      "resizeBy",
      "resizeTo",
      "screen",
      "screenLeft",
      "screenTop",
      "screenX",
      "screenY",
      "scroll",
      "scrollbars",
      "scrollBy",
      "scrollTo",
      "scrollX",
      "scrollY",
      "stop",
      "visualViewport",
      "window",
    ],
    /** Observer APIs: intersection, mutation, resize, reporting. */
    observers: ["IntersectionObserver", "MutationObserver", "ReportingObserver", "ResizeObserver"],
    /** Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group. */
    // rest: [],
  },
  auxiliary: {
    /** Deprecated or legacy browser globals. Direct entries are callable/readable but still not recommended. */
    deprecated: [
      "blur",
      "captureEvents",
      "clientInformation",
      "escape",
      "external",
      "orientation",
      "releaseEvents",
      "status",
      "unescape",
      "AudioProcessingEvent",
      "event",
      "External",
      "HTMLDirectoryElement",
      "HTMLFontElement",
      "HTMLFrameElement",
      "HTMLFrameSetElement",
      "HTMLMarqueeElement",
      "HTMLParamElement",
      "MimeType",
      "MimeTypeArray",
      "onkeypress",
      "onorientationchange",
      "onunload",
      "onwebkitanimationend",
      "onwebkitanimationiteration",
      "onwebkitanimationstart",
      "onwebkittransitionend",
      "PerformanceNavigation",
      "PerformanceTiming",
      "Plugin",
      "PluginArray",
      "ScriptProcessorNode",
      "TextEvent",
    ],
    /** ECMAScript language globals exposed through window/globalThis. */
    js: [
      "AggregateError",
      "Error",
      "EvalError",
      "RangeError",
      "ReferenceError",
      "SyntaxError",
      "TypeError",
      "URIError",
    ],
    /** Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers. */
    data: ["BlobEvent", "DOMStringList", "DOMStringMap", "FileList", "FormDataEvent", "ImageBitmap"],
    /** WHATWG stream primitives. */
    streams: [
      "ReadableByteStreamController",
      "ReadableStreamBYOBReader",
      "ReadableStreamBYOBRequest",
      "ReadableStreamDefaultController",
      "ReadableStreamDefaultReader",
      "TransformStreamDefaultController",
      "WritableStreamDefaultController",
      "WritableStreamDefaultWriter",
    ],
    /** Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging. */
    net: [
      "MessageEvent",
      "MessagePort",
      "Origin",
      "WebTransportBidirectionalStream",
      "WebTransportDatagramDuplexStream",
      "WebTransportError",
      "WebTransportReceiveStream",
      "WebTransportSendStream",
      "XMLHttpRequestEventTarget",
      "XMLHttpRequestUpload",
    ],
    /** Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks. */
    storage: [
      "Cache",
      "CacheStorage",
      "CookieChangeEvent",
      "CookieStore",
      "CookieStoreManager",
      "FileSystem",
      "FileSystemDirectoryEntry",
      "FileSystemDirectoryHandle",
      "FileSystemDirectoryReader",
      "FileSystemEntry",
      "FileSystemFileEntry",
      "FileSystemFileHandle",
      "FileSystemHandle",
      "FileSystemWritableFileStream",
      "IDBCursor",
      "IDBCursorWithValue",
      "IDBDatabase",
      "IDBFactory",
      "IDBIndex",
      "IDBObjectStore",
      "IDBOpenDBRequest",
      "IDBRequest",
      "IDBTransaction",
      "IDBVersionChangeEvent",
      "Lock",
      "LockManager",
      "Storage",
      "StorageEvent",
      "StorageManager",
    ],
    /** Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT. */
    dom: [
      "Comment",
      "Document",
      "DocumentFragment",
      "DOMMatrix",
      "DOMMatrixReadOnly",
      "DOMPoint",
      "DOMPointReadOnly",
      "DOMQuad",
      "DOMRect",
      "DOMRectReadOnly",
      "Image",
      "NodeFilter",
      "Option",
      "Range",
      "Sanitizer",
      "StaticRange",
      "AbstractRange",
      "Attr",
      "CaretPosition",
      "CDATASection",
      "CharacterData",
      "CustomElementRegistry",
      "CustomStateSet",
      "DocumentType",
      "DOMException",
      "DOMImplementation",
      "DOMRectList",
      "DOMTokenList",
      "Element",
      "ElementInternals",
      "FragmentDirective",
      "MathMLElement",
      "NamedNodeMap",
      "Node",
      "NodeIterator",
      "NodeList",
      "ProcessingInstruction",
      "RadioNodeList",
      "Selection",
      "ShadowRoot",
      "TreeWalker",
      "ValidityState",
      "XMLDocument",
      "XPathExpression",
      "XPathResult",
    ],
    /** HTML element constructors and related HTML collections/factories. */
    html: [
      "HTMLAllCollection",
      "HTMLAnchorElement",
      "HTMLAreaElement",
      "HTMLAudioElement",
      "HTMLBaseElement",
      "HTMLBodyElement",
      "HTMLBRElement",
      "HTMLButtonElement",
      "HTMLCanvasElement",
      "HTMLCollection",
      "HTMLDataElement",
      "HTMLDataListElement",
      "HTMLDetailsElement",
      "HTMLDialogElement",
      "HTMLDivElement",
      "HTMLDListElement",
      "HTMLDocument",
      "HTMLElement",
      "HTMLEmbedElement",
      "HTMLFieldSetElement",
      "HTMLFormControlsCollection",
      "HTMLFormElement",
      "HTMLHeadElement",
      "HTMLHeadingElement",
      "HTMLHRElement",
      "HTMLHtmlElement",
      "HTMLIFrameElement",
      "HTMLImageElement",
      "HTMLInputElement",
      "HTMLLabelElement",
      "HTMLLegendElement",
      "HTMLLIElement",
      "HTMLLinkElement",
      "HTMLMapElement",
      "HTMLMediaElement",
      "HTMLMenuElement",
      "HTMLMetaElement",
      "HTMLMeterElement",
      "HTMLModElement",
      "HTMLObjectElement",
      "HTMLOListElement",
      "HTMLOptGroupElement",
      "HTMLOptionElement",
      "HTMLOptionsCollection",
      "HTMLOutputElement",
      "HTMLParagraphElement",
      "HTMLPictureElement",
      "HTMLPreElement",
      "HTMLProgressElement",
      "HTMLQuoteElement",
      "HTMLScriptElement",
      "HTMLSelectElement",
      "HTMLSlotElement",
      "HTMLSourceElement",
      "HTMLSpanElement",
      "HTMLStyleElement",
      "HTMLTableCaptionElement",
      "HTMLTableCellElement",
      "HTMLTableColElement",
      "HTMLTableElement",
      "HTMLTableRowElement",
      "HTMLTableSectionElement",
      "HTMLTemplateElement",
      "HTMLTextAreaElement",
      "HTMLTimeElement",
      "HTMLTitleElement",
      "HTMLTrackElement",
      "HTMLUListElement",
      "HTMLUnknownElement",
      "HTMLVideoElement",
    ],
    /** CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights. */
    css: [
      "CSS",
      "CSSKeywordValue",
      "CSSMathClamp",
      "CSSMathInvert",
      "CSSMathMax",
      "CSSMathMin",
      "CSSMathNegate",
      "CSSMathProduct",
      "CSSMathSum",
      "CSSMatrixComponent",
      "CSSNumericValue",
      "CSSPerspective",
      "CSSRotate",
      "CSSScale",
      "CSSSkew",
      "CSSSkewX",
      "CSSSkewY",
      "CSSStyleSheet",
      "CSSStyleValue",
      "CSSTransformComponent",
      "CSSTransformValue",
      "CSSTranslate",
      "CSSUnitValue",
      "CSSUnparsedValue",
      "CSSVariableReferenceValue",
      "FontFace",
      "Highlight",
      "CSSAnimation",
      "CSSConditionRule",
      "CSSContainerRule",
      "CSSCounterStyleRule",
      "CSSFontFaceDescriptors",
      "CSSFontFaceRule",
      "CSSFontFeatureValuesRule",
      "CSSFontPaletteValuesRule",
      "CSSGroupingRule",
      "CSSImageValue",
      "CSSImportRule",
      "CSSKeyframeRule",
      "CSSKeyframesRule",
      "CSSLayerBlockRule",
      "CSSLayerStatementRule",
      "CSSMathValue",
      "CSSMediaRule",
      "CSSNamespaceRule",
      "CSSNestedDeclarations",
      "CSSNumericArray",
      "CSSPageDescriptors",
      "CSSPageRule",
      "CSSPositionTryDescriptors",
      "CSSPositionTryRule",
      "CSSPropertyRule",
      "CSSRule",
      "CSSRuleList",
      "CSSScopeRule",
      "CSSStartingStyleRule",
      "CSSStyleDeclaration",
      "CSSStyleProperties",
      "CSSStyleRule",
      "CSSSupportsRule",
      "CSSTransition",
      "CSSViewTransitionRule",
      "FontFaceSet",
      "FontFaceSetLoadEvent",
      "HighlightRegistry",
      "MediaList",
      "MediaQueryList",
      "MediaQueryListEvent",
      "StylePropertyMap",
      "StylePropertyMapReadOnly",
      "StyleSheet",
      "StyleSheetList",
      "WebKitCSSMatrix",
    ],
    /** SVG element constructors and SVG value/list helper objects. */
    svg: [
      "SVGAElement",
      "SVGAngle",
      "SVGAnimatedAngle",
      "SVGAnimatedBoolean",
      "SVGAnimatedEnumeration",
      "SVGAnimatedInteger",
      "SVGAnimatedLength",
      "SVGAnimatedLengthList",
      "SVGAnimatedNumber",
      "SVGAnimatedNumberList",
      "SVGAnimatedPreserveAspectRatio",
      "SVGAnimatedRect",
      "SVGAnimatedString",
      "SVGAnimatedTransformList",
      "SVGAnimateElement",
      "SVGAnimateMotionElement",
      "SVGAnimateTransformElement",
      "SVGAnimationElement",
      "SVGCircleElement",
      "SVGClipPathElement",
      "SVGComponentTransferFunctionElement",
      "SVGDefsElement",
      "SVGDescElement",
      "SVGElement",
      "SVGEllipseElement",
      "SVGFEBlendElement",
      "SVGFEColorMatrixElement",
      "SVGFEComponentTransferElement",
      "SVGFECompositeElement",
      "SVGFEConvolveMatrixElement",
      "SVGFEDiffuseLightingElement",
      "SVGFEDisplacementMapElement",
      "SVGFEDistantLightElement",
      "SVGFEDropShadowElement",
      "SVGFEFloodElement",
      "SVGFEFuncAElement",
      "SVGFEFuncBElement",
      "SVGFEFuncGElement",
      "SVGFEFuncRElement",
      "SVGFEGaussianBlurElement",
      "SVGFEImageElement",
      "SVGFEMergeElement",
      "SVGFEMergeNodeElement",
      "SVGFEMorphologyElement",
      "SVGFEOffsetElement",
      "SVGFEPointLightElement",
      "SVGFESpecularLightingElement",
      "SVGFESpotLightElement",
      "SVGFETileElement",
      "SVGFETurbulenceElement",
      "SVGFilterElement",
      "SVGForeignObjectElement",
      "SVGGElement",
      "SVGGeometryElement",
      "SVGGradientElement",
      "SVGGraphicsElement",
      "SVGImageElement",
      "SVGLength",
      "SVGLengthList",
      "SVGLinearGradientElement",
      "SVGLineElement",
      "SVGMarkerElement",
      "SVGMaskElement",
      "SVGMatrix",
      "SVGMetadataElement",
      "SVGMPathElement",
      "SVGNumber",
      "SVGNumberList",
      "SVGPathElement",
      "SVGPatternElement",
      "SVGPoint",
      "SVGPointList",
      "SVGPolygonElement",
      "SVGPolylineElement",
      "SVGPreserveAspectRatio",
      "SVGRadialGradientElement",
      "SVGRect",
      "SVGRectElement",
      "SVGScriptElement",
      "SVGSetElement",
      "SVGStopElement",
      "SVGStringList",
      "SVGStyleElement",
      "SVGSVGElement",
      "SVGSwitchElement",
      "SVGSymbolElement",
      "SVGTextContentElement",
      "SVGTextElement",
      "SVGTextPathElement",
      "SVGTextPositioningElement",
      "SVGTitleElement",
      "SVGTransform",
      "SVGTransformList",
      "SVGTSpanElement",
      "SVGUnitTypes",
      "SVGUseElement",
      "SVGViewElement",
    ],
    /** 2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics. */
    canvas: [
      "OffscreenCanvas",
      "Path2D",
      "CanvasCaptureMediaStreamTrack",
      "CanvasGradient",
      "CanvasPattern",
      "CanvasRenderingContext2D",
      "ImageBitmapRenderingContext",
      "OffscreenCanvasRenderingContext2D",
      "TextMetrics",
    ],
    /** WebGL rendering contexts and WebGL resource/event constructors. */
    webgl: [
      "WebGL2RenderingContext",
      "WebGLActiveInfo",
      "WebGLBuffer",
      "WebGLContextEvent",
      "WebGLFramebuffer",
      "WebGLProgram",
      "WebGLQuery",
      "WebGLRenderbuffer",
      "WebGLRenderingContext",
      "WebGLSampler",
      "WebGLShader",
      "WebGLShaderPrecisionFormat",
      "WebGLSync",
      "WebGLTexture",
      "WebGLTransformFeedback",
      "WebGLUniformLocation",
      "WebGLVertexArrayObject",
    ],
    /** WebGPU objects, constants, errors, resources, pipelines, queues, textures, and WGSL features. */
    webgpu: [
      "GPUBufferUsage",
      "GPUColorWrite",
      "GPUMapMode",
      "GPUShaderStage",
      "GPUTextureUsage",
      "GPU",
      "GPUAdapter",
      "GPUAdapterInfo",
      "GPUBindGroup",
      "GPUBindGroupLayout",
      "GPUBuffer",
      "GPUCanvasContext",
      "GPUCommandBuffer",
      "GPUCommandEncoder",
      "GPUCompilationInfo",
      "GPUCompilationMessage",
      "GPUComputePassEncoder",
      "GPUComputePipeline",
      "GPUDevice",
      "GPUDeviceLostInfo",
      "GPUError",
      "GPUExternalTexture",
      "GPUInternalError",
      "GPUOutOfMemoryError",
      "GPUPipelineError",
      "GPUPipelineLayout",
      "GPUQuerySet",
      "GPUQueue",
      "GPURenderBundle",
      "GPURenderBundleEncoder",
      "GPURenderPassEncoder",
      "GPURenderPipeline",
      "GPUSampler",
      "GPUShaderModule",
      "GPUSupportedFeatures",
      "GPUSupportedLimits",
      "GPUTexture",
      "GPUTextureView",
      "GPUUncapturedErrorEvent",
      "GPUValidationError",
      "WGSLLanguageFeatures",
    ],
    /** Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers. */
    audio: [
      "AudioDestinationNode",
      "AudioListener",
      "AudioNode",
      "AudioParam",
      "AudioParamMap",
      "AudioScheduledSourceNode",
      "AudioWorklet",
      "BaseAudioContext",
      "OfflineAudioCompletionEvent",
    ],
    /** Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis. */
    media: [
      "AudioData",
      "AudioDecoder",
      "AudioEncoder",
      "DocumentPictureInPicture",
      "DocumentPictureInPictureEvent",
      "EncodedAudioChunk",
      "EncodedVideoChunk",
      "ImageCapture",
      "ImageDecoder",
      "MediaMetadata",
      "VideoColorSpace",
      "VideoDecoder",
      "VideoEncoder",
      "VideoFrame",
      "VTTCue",
      "VTTRegion",
      "ImageTrack",
      "ImageTrackList",
      "MediaCapabilities",
      "MediaDeviceInfo",
      "MediaDevices",
      "MediaEncryptedEvent",
      "MediaError",
      "MediaKeyMessageEvent",
      "MediaKeys",
      "MediaKeySession",
      "MediaKeyStatusMap",
      "MediaKeySystemAccess",
      "MediaSession",
      "MediaSourceHandle",
      "MediaStreamTrack",
      "MediaStreamTrackEvent",
      "OverconstrainedError",
      "PictureInPictureEvent",
      "PictureInPictureWindow",
      "RemotePlayback",
      "SourceBuffer",
      "SourceBufferList",
      "SpeechSynthesis",
      "SpeechSynthesisErrorEvent",
      "SpeechSynthesisEvent",
      "SpeechSynthesisVoice",
      "TextTrack",
      "TextTrackCue",
      "TextTrackCueList",
      "TextTrackList",
      "TimeRanges",
      "TrackEvent",
      "VideoPlaybackQuality",
    ],
    /** WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors. */
    rtc: [
      "RTCCertificate",
      "RTCDataChannel",
      "RTCDataChannelEvent",
      "RTCDtlsTransport",
      "RTCDTMFSender",
      "RTCDTMFToneChangeEvent",
      "RTCEncodedAudioFrame",
      "RTCEncodedVideoFrame",
      "RTCError",
      "RTCErrorEvent",
      "RTCIceCandidate",
      "RTCIceTransport",
      "RTCPeerConnectionIceErrorEvent",
      "RTCPeerConnectionIceEvent",
      "RTCRtpReceiver",
      "RTCRtpScriptTransform",
      "RTCRtpSender",
      "RTCRtpTransceiver",
      "RTCSctpTransport",
      "RTCSessionDescription",
      "RTCStatsReport",
      "RTCTrackEvent",
    ],
    /** Global event handler slots plus general event constructors and event listener methods. */
    events: [
      "AnimationEvent",
      "AnimationPlaybackEvent",
      "BeforeUnloadEvent",
      "CloseEvent",
      "CommandEvent",
      "ContentVisibilityAutoStateChangeEvent",
      "CustomEvent",
      "DeviceMotionEvent",
      "DeviceOrientationEvent",
      "ErrorEvent",
      "Event",
      "EventCounts",
      "GamepadEvent",
      "HashChangeEvent",
      "MIDIConnectionEvent",
      "MIDIMessageEvent",
      "onabort",
      "onafterprint",
      "onanimationcancel",
      "onanimationend",
      "onanimationiteration",
      "onanimationstart",
      "onauxclick",
      "onbeforeinput",
      "onbeforematch",
      "onbeforeprint",
      "onbeforetoggle",
      "onbeforeunload",
      "onblur",
      "oncancel",
      "oncanplay",
      "oncanplaythrough",
      "onchange",
      "onclick",
      "onclose",
      "oncommand",
      "oncontextlost",
      "oncontextmenu",
      "oncontextrestored",
      "oncopy",
      "oncuechange",
      "oncut",
      "ondblclick",
      "ondevicemotion",
      "ondeviceorientation",
      "ondeviceorientationabsolute",
      "ondrag",
      "ondragend",
      "ondragenter",
      "ondragleave",
      "ondragover",
      "ondragstart",
      "ondrop",
      "ondurationchange",
      "onemptied",
      "onended",
      "onerror",
      "onfocus",
      "onformdata",
      "ongamepadconnected",
      "ongamepaddisconnected",
      "ongotpointercapture",
      "onhashchange",
      "oninput",
      "oninvalid",
      "onkeydown",
      "onkeyup",
      "onlanguagechange",
      "onload",
      "onloadeddata",
      "onloadedmetadata",
      "onloadstart",
      "onlostpointercapture",
      "onmessage",
      "onmessageerror",
      "onmousedown",
      "onmouseenter",
      "onmouseleave",
      "onmousemove",
      "onmouseout",
      "onmouseover",
      "onmouseup",
      "onoffline",
      "ononline",
      "onpagehide",
      "onpagereveal",
      "onpageshow",
      "onpageswap",
      "onpaste",
      "onpause",
      "onplay",
      "onplaying",
      "onpointercancel",
      "onpointerdown",
      "onpointerenter",
      "onpointerleave",
      "onpointermove",
      "onpointerout",
      "onpointerover",
      "onpointerrawupdate",
      "onpointerup",
      "onpopstate",
      "onprogress",
      "onratechange",
      "onrejectionhandled",
      "onreset",
      "onresize",
      "onscroll",
      "onscrollend",
      "onsecuritypolicyviolation",
      "onseeked",
      "onseeking",
      "onselect",
      "onselectionchange",
      "onselectstart",
      "onslotchange",
      "onstalled",
      "onstorage",
      "onsubmit",
      "onsuspend",
      "ontimeupdate",
      "ontoggle",
      "ontouchcancel",
      "ontouchend",
      "ontouchmove",
      "ontouchstart",
      "ontransitioncancel",
      "ontransitionend",
      "ontransitionrun",
      "ontransitionstart",
      "onunhandledrejection",
      "onvolumechange",
      "onwaiting",
      "onwheel",
      "PageRevealEvent",
      "PageSwapEvent",
      "PageTransitionEvent",
      "PopStateEvent",
      "ProgressEvent",
      "PromiseRejectionEvent",
      "SubmitEvent",
      "ToggleEvent",
      "TransitionEvent",
      "UIEvent",
    ],
    /** Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input. */
    input: [
      "Clipboard",
      "ClipboardEvent",
      "CompositionEvent",
      "DataTransferItem",
      "DataTransferItemList",
      "DragEvent",
      "FocusEvent",
      "Gamepad",
      "GamepadButton",
      "GamepadHapticActuator",
      "InputDeviceInfo",
      "InputEvent",
      "KeyboardEvent",
      "MouseEvent",
      "PointerEvent",
      "Touch",
      "TouchEvent",
      "TouchList",
      "WheelEvent",
    ],
    /** Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF. */
    animation: [
      "Animation",
      "DocumentTimeline",
      "KeyframeEffect",
      "ScrollTimeline",
      "ViewTimeline",
      "AnimationEffect",
      "AnimationTimeline",
      "ViewTransition",
      "ViewTransitionTypeSet",
    ],
    /** Performance timeline, observer, navigation/resource/paint/event timing, LCP. */
    performance: [
      "LargestContentfulPaint",
      "Performance",
      "PerformanceEntry",
      "PerformanceEventTiming",
      "PerformanceMark",
      "PerformanceMeasure",
      "PerformanceNavigationTiming",
      "PerformanceObserverEntryList",
      "PerformancePaintTiming",
      "PerformanceResourceTiming",
      "PerformanceServerTiming",
    ],
    /** Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting. */
    scheduling: ["IdleDeadline", "Scheduler", "TaskPriorityChangeEvent", "TaskSignal"],
    /** Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals. */
    workers: [
      "PushManager",
      "PushSubscription",
      "PushSubscriptionOptions",
      "ServiceWorker",
      "ServiceWorkerContainer",
      "ServiceWorkerRegistration",
      "Worklet",
    ],
    /** Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event. */
    security: [
      "AuthenticatorAssertionResponse",
      "AuthenticatorAttestationResponse",
      "AuthenticatorResponse",
      "Credential",
      "CredentialsContainer",
      "Crypto",
      "CryptoKey",
      "DigitalCredential",
      "Permissions",
      "PermissionStatus",
      "SecurityPolicyViolationEvent",
      "SubtleCrypto",
    ],
    /** Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint. */
    nav: [
      "Geolocation",
      "GeolocationCoordinates",
      "GeolocationPosition",
      "GeolocationPositionError",
      "MIDIAccess",
      "MIDIInput",
      "MIDIInputMap",
      "MIDIOutput",
      "MIDIOutputMap",
      "MIDIPort",
      "Navigator",
      "NavigatorLogin",
      "Serial",
      "SerialPort",
      "UserActivation",
      "WakeLock",
      "WakeLockSentinel",
    ],
    /** Payment Request API globals. */
    payment: ["PaymentAddress", "PaymentMethodChangeEvent", "PaymentRequestUpdateEvent", "PaymentResponse"],
    /** Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals. */
    ui: [
      "alert",
      "closed",
      "CloseWatcher",
      "confirm",
      "focus",
      "frameElement",
      "frames",
      "length",
      "locationbar",
      "menubar",
      "moveBy",
      "moveTo",
      "name",
      "navigation",
      "outerHeight",
      "outerWidth",
      "pageXOffset",
      "pageYOffset",
      "personalbar",
      "prompt",
      "toolbar",
      "top",
      "toString",
      "self",
      "statusbar",
      "BarProp",
      "History",
      "Location",
      "NavigateEvent",
      "Navigation",
      "NavigationActivation",
      "NavigationCurrentEntryChangeEvent",
      "NavigationDestination",
      "NavigationHistoryEntry",
      "NavigationPrecommitController",
      "NavigationPreloadManager",
      "NavigationTransition",
      "Screen",
      "ScreenOrientation",
      "VisualViewport",
      "Window",
    ],
    /** Observer APIs: intersection, mutation, resize, reporting. */
    observers: ["IntersectionObserverEntry", "MutationRecord", "ResizeObserverEntry", "ResizeObserverSize"],
    /** Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group. */
    rest: [
      "SpeechRecognitionAlternative",
      "SpeechRecognitionErrorEvent",
      "SpeechRecognitionEvent",
      "SpeechRecognitionResult",
      "SpeechRecognitionResultList",
      "webkitURL",
    ],
  },
} as const satisfies Record<WindowUsageKind, Partial<Record<WindowGroupName, readonly WindowKey[]>>>;

export const mainWindowGroups = windowUsageGroups.main;
export const auxiliaryWindowGroups = windowUsageGroups.auxiliary;

type Values<T> = T[keyof T];
type TupleItem<T> = T extends readonly (infer I)[] ? I : never;

export type DirectWindowKey = TupleItem<Values<typeof mainWindowGroups>>;
export type auxiliaryWindowKey = TupleItem<Values<typeof auxiliaryWindowGroups>>;
export type GroupedWindowKey = DirectWindowKey | auxiliaryWindowKey;

export type MissingWindowKey = Exclude<WindowKey, GroupedWindowKey>;
export type UnknownWindowKey = Exclude<GroupedWindowKey, WindowKey>;
export type OverlappedWindowKey = Extract<DirectWindowKey, auxiliaryWindowKey>;

// These fail compilation if the installed DOM/lib version has drifted or the split is wrong.
type AssertNever<T extends never> = T;
export type _AllWindowKeysAreGrouped = AssertNever<MissingWindowKey>;
export type _NoUnknownWindowKeys = AssertNever<UnknownWindowKey>;
export type _NoDirectauxiliaryOverlap = AssertNever<OverlappedWindowKey>;
