/**
 * Generated grouping of keys on `window` from:
 *   keyof (Window & typeof globalThis)
 *
 * Source package used for extraction:
 *   @types/web@0.0.352
 *   typescript@6.0.3
 *
 * Notes:
 * - `window` is declared as `Window & typeof globalThis`, so JS globals such as
 *   `Array`, `Math`, `Promise`, `parseInt`, etc. are included.
 * - The `deprecated` group is based on declarations carrying `@deprecated`.
 * - `rest` intentionally contains rare/vendor/niche leftovers.
 */

export type WindowKey = keyof (Window & typeof globalThis) & string;

export const windowGroups = {
  /** Marked @deprecated in @types/web / TypeScript declarations. Legacy browser globals and obsolete DOM APIs. */
  deprecated: [
    "AudioProcessingEvent",
    "blur",
    "captureEvents",
    "clientInformation",
    "escape",
    "event",
    "external",
    "External",
    "HTMLDirectoryElement",
    "HTMLFontElement",
    "HTMLFrameElement",
    "HTMLFrameSetElement",
    "HTMLMarqueeElement",
    "HTMLParamElement",
    "MimeType",
    "MimeTypeArray",
    "onkeypress",
    "onorientationchange",
    "onunload",
    "onwebkitanimationend",
    "onwebkitanimationiteration",
    "onwebkitanimationstart",
    "onwebkittransitionend",
    "orientation",
    "PerformanceNavigation",
    "PerformanceTiming",
    "Plugin",
    "PluginArray",
    "releaseEvents",
    "ScriptProcessorNode",
    "status",
    "TextEvent",
    "unescape",
  ],
  /** ECMAScript language globals exposed through window because window is Window & typeof globalThis. */
  js: [
    "AggregateError",
    "Array",
    "ArrayBuffer",
    "Atomics",
    "BigInt",
    "BigInt64Array",
    "BigUint64Array",
    "Boolean",
    "console",
    "DataView",
    "Date",
    "decodeURI",
    "decodeURIComponent",
    "encodeURI",
    "encodeURIComponent",
    "Error",
    "eval",
    "EvalError",
    "FinalizationRegistry",
    "Float32Array",
    "Float64Array",
    "Function",
    "globalThis",
    "Infinity",
    "Int16Array",
    "Int32Array",
    "Int8Array",
    "Intl",
    "isFinite",
    "isNaN",
    "JSON",
    "Map",
    "Math",
    "NaN",
    "Number",
    "Object",
    "parseFloat",
    "parseInt",
    "Promise",
    "Proxy",
    "RangeError",
    "ReferenceError",
    "Reflect",
    "RegExp",
    "Set",
    "SharedArrayBuffer",
    "String",
    "Symbol",
    "SyntaxError",
    "TypeError",
    "Uint16Array",
    "Uint32Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "undefined",
    "URIError",
    "WeakMap",
    "WeakRef",
    "WeakSet",
    "WebAssembly",
  ],
  /** Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers. */
  data: [
    "atob",
    "Blob",
    "BlobEvent",
    "btoa",
    "ByteLengthQueuingStrategy",
    "CompressionStream",
    "CountQueuingStrategy",
    "createImageBitmap",
    "DecompressionStream",
    "DOMStringList",
    "DOMStringMap",
    "File",
    "FileList",
    "FileReader",
    "FormData",
    "FormDataEvent",
    "ImageBitmap",
    "ImageData",
    "structuredClone",
    "TextDecoder",
    "TextDecoderStream",
    "TextEncoder",
    "TextEncoderStream",
    "URL",
    "URLPattern",
    "URLSearchParams",
  ],
  /** WHATWG stream primitives. */
  streams: [
    "ReadableByteStreamController",
    "ReadableStream",
    "ReadableStreamBYOBReader",
    "ReadableStreamBYOBRequest",
    "ReadableStreamDefaultController",
    "ReadableStreamDefaultReader",
    "TransformStream",
    "TransformStreamDefaultController",
    "WritableStream",
    "WritableStreamDefaultController",
    "WritableStreamDefaultWriter",
  ],
  /** Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging. */
  net: [
    "BroadcastChannel",
    "EventSource",
    "fetch",
    "Headers",
    "MessageChannel",
    "MessageEvent",
    "MessagePort",
    "origin",
    "Origin",
    "postMessage",
    "Request",
    "Response",
    "WebSocket",
    "WebTransport",
    "WebTransportBidirectionalStream",
    "WebTransportDatagramDuplexStream",
    "WebTransportError",
    "WebTransportReceiveStream",
    "WebTransportSendStream",
    "XMLHttpRequest",
    "XMLHttpRequestEventTarget",
    "XMLHttpRequestUpload",
  ],
  /** Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks. */
  storage: [
    "Cache",
    "caches",
    "CacheStorage",
    "CookieChangeEvent",
    "cookieStore",
    "CookieStore",
    "CookieStoreManager",
    "FileSystem",
    "FileSystemDirectoryEntry",
    "FileSystemDirectoryHandle",
    "FileSystemDirectoryReader",
    "FileSystemEntry",
    "FileSystemFileEntry",
    "FileSystemFileHandle",
    "FileSystemHandle",
    "FileSystemWritableFileStream",
    "IDBCursor",
    "IDBCursorWithValue",
    "IDBDatabase",
    "IDBFactory",
    "IDBIndex",
    "IDBKeyRange",
    "IDBObjectStore",
    "IDBOpenDBRequest",
    "IDBRequest",
    "IDBTransaction",
    "IDBVersionChangeEvent",
    "indexedDB",
    "localStorage",
    "Lock",
    "LockManager",
    "sessionStorage",
    "Storage",
    "StorageEvent",
    "StorageManager",
  ],
  /** Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT. */
  dom: [
    "AbstractRange",
    "Attr",
    "CaretPosition",
    "CDATASection",
    "CharacterData",
    "Comment",
    "CustomElementRegistry",
    "customElements",
    "CustomStateSet",
    "document",
    "Document",
    "DocumentFragment",
    "DocumentType",
    "DOMException",
    "DOMImplementation",
    "DOMMatrix",
    "DOMMatrixReadOnly",
    "DOMParser",
    "DOMPoint",
    "DOMPointReadOnly",
    "DOMQuad",
    "DOMRect",
    "DOMRectList",
    "DOMRectReadOnly",
    "DOMTokenList",
    "Element",
    "ElementInternals",
    "FragmentDirective",
    "Image",
    "MathMLElement",
    "NamedNodeMap",
    "Node",
    "NodeFilter",
    "NodeIterator",
    "NodeList",
    "Option",
    "ProcessingInstruction",
    "RadioNodeList",
    "Range",
    "Sanitizer",
    "Selection",
    "ShadowRoot",
    "StaticRange",
    "Text",
    "TreeWalker",
    "ValidityState",
    "XMLDocument",
    "XMLSerializer",
    "XPathEvaluator",
    "XPathExpression",
    "XPathResult",
    "XSLTProcessor",
  ],
  /** HTML element constructors and related HTML collections/factories. */
  html: [
    "HTMLAllCollection",
    "HTMLAnchorElement",
    "HTMLAreaElement",
    "HTMLAudioElement",
    "HTMLBaseElement",
    "HTMLBodyElement",
    "HTMLBRElement",
    "HTMLButtonElement",
    "HTMLCanvasElement",
    "HTMLCollection",
    "HTMLDataElement",
    "HTMLDataListElement",
    "HTMLDetailsElement",
    "HTMLDialogElement",
    "HTMLDivElement",
    "HTMLDListElement",
    "HTMLDocument",
    "HTMLElement",
    "HTMLEmbedElement",
    "HTMLFieldSetElement",
    "HTMLFormControlsCollection",
    "HTMLFormElement",
    "HTMLHeadElement",
    "HTMLHeadingElement",
    "HTMLHRElement",
    "HTMLHtmlElement",
    "HTMLIFrameElement",
    "HTMLImageElement",
    "HTMLInputElement",
    "HTMLLabelElement",
    "HTMLLegendElement",
    "HTMLLIElement",
    "HTMLLinkElement",
    "HTMLMapElement",
    "HTMLMediaElement",
    "HTMLMenuElement",
    "HTMLMetaElement",
    "HTMLMeterElement",
    "HTMLModElement",
    "HTMLObjectElement",
    "HTMLOListElement",
    "HTMLOptGroupElement",
    "HTMLOptionElement",
    "HTMLOptionsCollection",
    "HTMLOutputElement",
    "HTMLParagraphElement",
    "HTMLPictureElement",
    "HTMLPreElement",
    "HTMLProgressElement",
    "HTMLQuoteElement",
    "HTMLScriptElement",
    "HTMLSelectElement",
    "HTMLSlotElement",
    "HTMLSourceElement",
    "HTMLSpanElement",
    "HTMLStyleElement",
    "HTMLTableCaptionElement",
    "HTMLTableCellElement",
    "HTMLTableColElement",
    "HTMLTableElement",
    "HTMLTableRowElement",
    "HTMLTableSectionElement",
    "HTMLTemplateElement",
    "HTMLTextAreaElement",
    "HTMLTimeElement",
    "HTMLTitleElement",
    "HTMLTrackElement",
    "HTMLUListElement",
    "HTMLUnknownElement",
    "HTMLVideoElement",
  ],
  /** CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights. */
  css: [
    "CSS",
    "CSSAnimation",
    "CSSConditionRule",
    "CSSContainerRule",
    "CSSCounterStyleRule",
    "CSSFontFaceDescriptors",
    "CSSFontFaceRule",
    "CSSFontFeatureValuesRule",
    "CSSFontPaletteValuesRule",
    "CSSGroupingRule",
    "CSSImageValue",
    "CSSImportRule",
    "CSSKeyframeRule",
    "CSSKeyframesRule",
    "CSSKeywordValue",
    "CSSLayerBlockRule",
    "CSSLayerStatementRule",
    "CSSMathClamp",
    "CSSMathInvert",
    "CSSMathMax",
    "CSSMathMin",
    "CSSMathNegate",
    "CSSMathProduct",
    "CSSMathSum",
    "CSSMathValue",
    "CSSMatrixComponent",
    "CSSMediaRule",
    "CSSNamespaceRule",
    "CSSNestedDeclarations",
    "CSSNumericArray",
    "CSSNumericValue",
    "CSSPageDescriptors",
    "CSSPageRule",
    "CSSPerspective",
    "CSSPositionTryDescriptors",
    "CSSPositionTryRule",
    "CSSPropertyRule",
    "CSSRotate",
    "CSSRule",
    "CSSRuleList",
    "CSSScale",
    "CSSScopeRule",
    "CSSSkew",
    "CSSSkewX",
    "CSSSkewY",
    "CSSStartingStyleRule",
    "CSSStyleDeclaration",
    "CSSStyleProperties",
    "CSSStyleRule",
    "CSSStyleSheet",
    "CSSStyleValue",
    "CSSSupportsRule",
    "CSSTransformComponent",
    "CSSTransformValue",
    "CSSTransition",
    "CSSTranslate",
    "CSSUnitValue",
    "CSSUnparsedValue",
    "CSSVariableReferenceValue",
    "CSSViewTransitionRule",
    "FontFace",
    "FontFaceSet",
    "FontFaceSetLoadEvent",
    "getComputedStyle",
    "Highlight",
    "HighlightRegistry",
    "matchMedia",
    "MediaList",
    "MediaQueryList",
    "MediaQueryListEvent",
    "StylePropertyMap",
    "StylePropertyMapReadOnly",
    "StyleSheet",
    "StyleSheetList",
    "WebKitCSSMatrix",
  ],
  /** SVG element constructors and SVG value/list helper objects. */
  svg: [
    "SVGAElement",
    "SVGAngle",
    "SVGAnimatedAngle",
    "SVGAnimatedBoolean",
    "SVGAnimatedEnumeration",
    "SVGAnimatedInteger",
    "SVGAnimatedLength",
    "SVGAnimatedLengthList",
    "SVGAnimatedNumber",
    "SVGAnimatedNumberList",
    "SVGAnimatedPreserveAspectRatio",
    "SVGAnimatedRect",
    "SVGAnimatedString",
    "SVGAnimatedTransformList",
    "SVGAnimateElement",
    "SVGAnimateMotionElement",
    "SVGAnimateTransformElement",
    "SVGAnimationElement",
    "SVGCircleElement",
    "SVGClipPathElement",
    "SVGComponentTransferFunctionElement",
    "SVGDefsElement",
    "SVGDescElement",
    "SVGElement",
    "SVGEllipseElement",
    "SVGFEBlendElement",
    "SVGFEColorMatrixElement",
    "SVGFEComponentTransferElement",
    "SVGFECompositeElement",
    "SVGFEConvolveMatrixElement",
    "SVGFEDiffuseLightingElement",
    "SVGFEDisplacementMapElement",
    "SVGFEDistantLightElement",
    "SVGFEDropShadowElement",
    "SVGFEFloodElement",
    "SVGFEFuncAElement",
    "SVGFEFuncBElement",
    "SVGFEFuncGElement",
    "SVGFEFuncRElement",
    "SVGFEGaussianBlurElement",
    "SVGFEImageElement",
    "SVGFEMergeElement",
    "SVGFEMergeNodeElement",
    "SVGFEMorphologyElement",
    "SVGFEOffsetElement",
    "SVGFEPointLightElement",
    "SVGFESpecularLightingElement",
    "SVGFESpotLightElement",
    "SVGFETileElement",
    "SVGFETurbulenceElement",
    "SVGFilterElement",
    "SVGForeignObjectElement",
    "SVGGElement",
    "SVGGeometryElement",
    "SVGGradientElement",
    "SVGGraphicsElement",
    "SVGImageElement",
    "SVGLength",
    "SVGLengthList",
    "SVGLinearGradientElement",
    "SVGLineElement",
    "SVGMarkerElement",
    "SVGMaskElement",
    "SVGMatrix",
    "SVGMetadataElement",
    "SVGMPathElement",
    "SVGNumber",
    "SVGNumberList",
    "SVGPathElement",
    "SVGPatternElement",
    "SVGPoint",
    "SVGPointList",
    "SVGPolygonElement",
    "SVGPolylineElement",
    "SVGPreserveAspectRatio",
    "SVGRadialGradientElement",
    "SVGRect",
    "SVGRectElement",
    "SVGScriptElement",
    "SVGSetElement",
    "SVGStopElement",
    "SVGStringList",
    "SVGStyleElement",
    "SVGSVGElement",
    "SVGSwitchElement",
    "SVGSymbolElement",
    "SVGTextContentElement",
    "SVGTextElement",
    "SVGTextPathElement",
    "SVGTextPositioningElement",
    "SVGTitleElement",
    "SVGTransform",
    "SVGTransformList",
    "SVGTSpanElement",
    "SVGUnitTypes",
    "SVGUseElement",
    "SVGViewElement",
  ],
  /** 2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics. */
  canvas: [
    "CanvasCaptureMediaStreamTrack",
    "CanvasGradient",
    "CanvasPattern",
    "CanvasRenderingContext2D",
    "ImageBitmapRenderingContext",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2D",
    "Path2D",
    "TextMetrics",
  ],
  /** WebGL rendering contexts and WebGL resource/event constructors. */
  webgl: [
    "WebGL2RenderingContext",
    "WebGLActiveInfo",
    "WebGLBuffer",
    "WebGLContextEvent",
    "WebGLFramebuffer",
    "WebGLProgram",
    "WebGLQuery",
    "WebGLRenderbuffer",
    "WebGLRenderingContext",
    "WebGLSampler",
    "WebGLShader",
    "WebGLShaderPrecisionFormat",
    "WebGLSync",
    "WebGLTexture",
    "WebGLTransformFeedback",
    "WebGLUniformLocation",
    "WebGLVertexArrayObject",
  ],
  /** WebGPU objects, enums, errors, resources, pipelines, queues, textures, and WGSL features. */
  webgpu: [
    "GPU",
    "GPUAdapter",
    "GPUAdapterInfo",
    "GPUBindGroup",
    "GPUBindGroupLayout",
    "GPUBuffer",
    "GPUBufferUsage",
    "GPUCanvasContext",
    "GPUColorWrite",
    "GPUCommandBuffer",
    "GPUCommandEncoder",
    "GPUCompilationInfo",
    "GPUCompilationMessage",
    "GPUComputePassEncoder",
    "GPUComputePipeline",
    "GPUDevice",
    "GPUDeviceLostInfo",
    "GPUError",
    "GPUExternalTexture",
    "GPUInternalError",
    "GPUMapMode",
    "GPUOutOfMemoryError",
    "GPUPipelineError",
    "GPUPipelineLayout",
    "GPUQuerySet",
    "GPUQueue",
    "GPURenderBundle",
    "GPURenderBundleEncoder",
    "GPURenderPassEncoder",
    "GPURenderPipeline",
    "GPUSampler",
    "GPUShaderModule",
    "GPUShaderStage",
    "GPUSupportedFeatures",
    "GPUSupportedLimits",
    "GPUTexture",
    "GPUTextureUsage",
    "GPUTextureView",
    "GPUUncapturedErrorEvent",
    "GPUValidationError",
    "WGSLLanguageFeatures",
  ],
  /** Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers. */
  audio: [
    "AnalyserNode",
    "Audio",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioContext",
    "AudioDestinationNode",
    "AudioListener",
    "AudioNode",
    "AudioParam",
    "AudioParamMap",
    "AudioScheduledSourceNode",
    "AudioWorklet",
    "AudioWorkletNode",
    "BaseAudioContext",
    "BiquadFilterNode",
    "ChannelMergerNode",
    "ChannelSplitterNode",
    "ConstantSourceNode",
    "ConvolverNode",
    "DelayNode",
    "DynamicsCompressorNode",
    "GainNode",
    "IIRFilterNode",
    "MediaElementAudioSourceNode",
    "MediaStreamAudioDestinationNode",
    "MediaStreamAudioSourceNode",
    "OfflineAudioCompletionEvent",
    "OfflineAudioContext",
    "OscillatorNode",
    "PannerNode",
    "PeriodicWave",
    "StereoPannerNode",
    "WaveShaperNode",
  ],
  /** Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis. */
  media: [
    "AudioData",
    "AudioDecoder",
    "AudioEncoder",
    "documentPictureInPicture",
    "DocumentPictureInPicture",
    "DocumentPictureInPictureEvent",
    "EncodedAudioChunk",
    "EncodedVideoChunk",
    "ImageCapture",
    "ImageDecoder",
    "ImageTrack",
    "ImageTrackList",
    "MediaCapabilities",
    "MediaDeviceInfo",
    "MediaDevices",
    "MediaEncryptedEvent",
    "MediaError",
    "MediaKeyMessageEvent",
    "MediaKeys",
    "MediaKeySession",
    "MediaKeyStatusMap",
    "MediaKeySystemAccess",
    "MediaMetadata",
    "MediaRecorder",
    "MediaSession",
    "MediaSource",
    "MediaSourceHandle",
    "MediaStream",
    "MediaStreamTrack",
    "MediaStreamTrackEvent",
    "OverconstrainedError",
    "PictureInPictureEvent",
    "PictureInPictureWindow",
    "RemotePlayback",
    "SourceBuffer",
    "SourceBufferList",
    "speechSynthesis",
    "SpeechSynthesis",
    "SpeechSynthesisErrorEvent",
    "SpeechSynthesisEvent",
    "SpeechSynthesisUtterance",
    "SpeechSynthesisVoice",
    "TextTrack",
    "TextTrackCue",
    "TextTrackCueList",
    "TextTrackList",
    "TimeRanges",
    "TrackEvent",
    "VideoColorSpace",
    "VideoDecoder",
    "VideoEncoder",
    "VideoFrame",
    "VideoPlaybackQuality",
    "VTTCue",
    "VTTRegion",
  ],
  /** WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors. */
  rtc: [
    "RTCCertificate",
    "RTCDataChannel",
    "RTCDataChannelEvent",
    "RTCDtlsTransport",
    "RTCDTMFSender",
    "RTCDTMFToneChangeEvent",
    "RTCEncodedAudioFrame",
    "RTCEncodedVideoFrame",
    "RTCError",
    "RTCErrorEvent",
    "RTCIceCandidate",
    "RTCIceTransport",
    "RTCPeerConnection",
    "RTCPeerConnectionIceErrorEvent",
    "RTCPeerConnectionIceEvent",
    "RTCRtpReceiver",
    "RTCRtpScriptTransform",
    "RTCRtpSender",
    "RTCRtpTransceiver",
    "RTCSctpTransport",
    "RTCSessionDescription",
    "RTCStatsReport",
    "RTCTrackEvent",
  ],
  /** Global event handler slots plus general event constructors and event listener methods. */
  events: [
    "addEventListener",
    "AnimationEvent",
    "AnimationPlaybackEvent",
    "BeforeUnloadEvent",
    "CloseEvent",
    "CommandEvent",
    "ContentVisibilityAutoStateChangeEvent",
    "CustomEvent",
    "DeviceMotionEvent",
    "DeviceOrientationEvent",
    "dispatchEvent",
    "ErrorEvent",
    "Event",
    "EventCounts",
    "EventTarget",
    "GamepadEvent",
    "HashChangeEvent",
    "MIDIConnectionEvent",
    "MIDIMessageEvent",
    "onabort",
    "onafterprint",
    "onanimationcancel",
    "onanimationend",
    "onanimationiteration",
    "onanimationstart",
    "onauxclick",
    "onbeforeinput",
    "onbeforematch",
    "onbeforeprint",
    "onbeforetoggle",
    "onbeforeunload",
    "onblur",
    "oncancel",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onclick",
    "onclose",
    "oncommand",
    "oncontextlost",
    "oncontextmenu",
    "oncontextrestored",
    "oncopy",
    "oncuechange",
    "oncut",
    "ondblclick",
    "ondevicemotion",
    "ondeviceorientation",
    "ondeviceorientationabsolute",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onended",
    "onerror",
    "onfocus",
    "onformdata",
    "ongamepadconnected",
    "ongamepaddisconnected",
    "ongotpointercapture",
    "onhashchange",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeyup",
    "onlanguagechange",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadstart",
    "onlostpointercapture",
    "onmessage",
    "onmessageerror",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpagereveal",
    "onpageshow",
    "onpageswap",
    "onpaste",
    "onpause",
    "onplay",
    "onplaying",
    "onpointercancel",
    "onpointerdown",
    "onpointerenter",
    "onpointerleave",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointerrawupdate",
    "onpointerup",
    "onpopstate",
    "onprogress",
    "onratechange",
    "onrejectionhandled",
    "onreset",
    "onresize",
    "onscroll",
    "onscrollend",
    "onsecuritypolicyviolation",
    "onseeked",
    "onseeking",
    "onselect",
    "onselectionchange",
    "onselectstart",
    "onslotchange",
    "onstalled",
    "onstorage",
    "onsubmit",
    "onsuspend",
    "ontimeupdate",
    "ontoggle",
    "ontouchcancel",
    "ontouchend",
    "ontouchmove",
    "ontouchstart",
    "ontransitioncancel",
    "ontransitionend",
    "ontransitionrun",
    "ontransitionstart",
    "onunhandledrejection",
    "onvolumechange",
    "onwaiting",
    "onwheel",
    "PageRevealEvent",
    "PageSwapEvent",
    "PageTransitionEvent",
    "PopStateEvent",
    "ProgressEvent",
    "PromiseRejectionEvent",
    "removeEventListener",
    "SubmitEvent",
    "ToggleEvent",
    "TransitionEvent",
    "UIEvent",
  ],
  /** Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input. */
  input: [
    "Clipboard",
    "ClipboardEvent",
    "ClipboardItem",
    "CompositionEvent",
    "DataTransfer",
    "DataTransferItem",
    "DataTransferItemList",
    "DragEvent",
    "FocusEvent",
    "Gamepad",
    "GamepadButton",
    "GamepadHapticActuator",
    "getSelection",
    "InputDeviceInfo",
    "InputEvent",
    "KeyboardEvent",
    "MouseEvent",
    "PointerEvent",
    "Touch",
    "TouchEvent",
    "TouchList",
    "WheelEvent",
  ],
  /** Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF. */
  animation: [
    "Animation",
    "AnimationEffect",
    "AnimationTimeline",
    "cancelAnimationFrame",
    "DocumentTimeline",
    "KeyframeEffect",
    "requestAnimationFrame",
    "ScrollTimeline",
    "ViewTimeline",
    "ViewTransition",
    "ViewTransitionTypeSet",
  ],
  /** Performance timeline, observer, navigation/resource/paint/event timing, LCP. */
  performance: [
    "LargestContentfulPaint",
    "performance",
    "Performance",
    "PerformanceEntry",
    "PerformanceEventTiming",
    "PerformanceMark",
    "PerformanceMeasure",
    "PerformanceNavigationTiming",
    "PerformanceObserver",
    "PerformanceObserverEntryList",
    "PerformancePaintTiming",
    "PerformanceResourceTiming",
    "PerformanceServerTiming",
  ],
  /** Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting. */
  scheduling: [
    "cancelIdleCallback",
    "clearInterval",
    "clearTimeout",
    "IdleDeadline",
    "queueMicrotask",
    "reportError",
    "requestIdleCallback",
    "scheduler",
    "Scheduler",
    "setInterval",
    "setTimeout",
    "TaskController",
    "TaskPriorityChangeEvent",
    "TaskSignal",
  ],
  /** Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals. */
  workers: [
    "Notification",
    "PushManager",
    "PushSubscription",
    "PushSubscriptionOptions",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "SharedWorker",
    "Worker",
    "Worklet",
  ],
  /** Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event. */
  security: [
    "AbortController",
    "AbortSignal",
    "AuthenticatorAssertionResponse",
    "AuthenticatorAttestationResponse",
    "AuthenticatorResponse",
    "Credential",
    "CredentialsContainer",
    "crossOriginIsolated",
    "crypto",
    "Crypto",
    "CryptoKey",
    "DigitalCredential",
    "isSecureContext",
    "originAgentCluster",
    "Permissions",
    "PermissionStatus",
    "PublicKeyCredential",
    "SecurityPolicyViolationEvent",
    "SubtleCrypto",
  ],
  /** Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint. */
  devices: [
    "Geolocation",
    "GeolocationCoordinates",
    "GeolocationPosition",
    "GeolocationPositionError",
    "MIDIAccess",
    "MIDIInput",
    "MIDIInputMap",
    "MIDIOutput",
    "MIDIOutputMap",
    "MIDIPort",
    "navigator",
    "Navigator",
    "NavigatorLogin",
    "Serial",
    "SerialPort",
    "UserActivation",
    "WakeLock",
    "WakeLockSentinel",
  ],
  /** Payment Request API globals. */
  payment: [
    "PaymentAddress",
    "PaymentMethodChangeEvent",
    "PaymentRequest",
    "PaymentRequestUpdateEvent",
    "PaymentResponse",
  ],
  /** Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals. */
  ui: [
    "alert",
    "BarProp",
    "close",
    "closed",
    "CloseWatcher",
    "confirm",
    "devicePixelRatio",
    "focus",
    "frameElement",
    "frames",
    "history",
    "History",
    "innerHeight",
    "innerWidth",
    "length",
    "location",
    "Location",
    "locationbar",
    "menubar",
    "moveBy",
    "moveTo",
    "name",
    "NavigateEvent",
    "navigation",
    "Navigation",
    "NavigationActivation",
    "NavigationCurrentEntryChangeEvent",
    "NavigationDestination",
    "NavigationHistoryEntry",
    "NavigationPrecommitController",
    "NavigationPreloadManager",
    "NavigationTransition",
    "open",
    "opener",
    "outerHeight",
    "outerWidth",
    "pageXOffset",
    "pageYOffset",
    "parent",
    "personalbar",
    "print",
    "prompt",
    "resizeBy",
    "resizeTo",
    "screen",
    "Screen",
    "screenLeft",
    "ScreenOrientation",
    "screenTop",
    "screenX",
    "screenY",
    "scroll",
    "scrollbars",
    "scrollBy",
    "scrollTo",
    "scrollX",
    "scrollY",
    "self",
    "statusbar",
    "stop",
    "toolbar",
    "top",
    "toString",
    "visualViewport",
    "VisualViewport",
    "window",
    "Window",
  ],
  /** Observer APIs: intersection, mutation, resize, reporting. */
  observers: [
    "IntersectionObserver",
    "IntersectionObserverEntry",
    "MutationObserver",
    "MutationRecord",
    "ReportingObserver",
    "ResizeObserver",
    "ResizeObserverEntry",
    "ResizeObserverSize",
  ],
  /** Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group. */
  rest: [
    "SpeechRecognitionAlternative",
    "SpeechRecognitionErrorEvent",
    "SpeechRecognitionEvent",
    "SpeechRecognitionResult",
    "SpeechRecognitionResultList",
    "webkitURL",
  ],
} as const satisfies Record<string, readonly WindowKey[]>;

export type WindowGroupName = keyof typeof windowGroups;

export const windowGroupDescriptions = {
  deprecated:
    "Marked @deprecated in @types/web / TypeScript declarations. Legacy browser globals and obsolete DOM APIs.",
  js: "ECMAScript language globals exposed through window because window is Window & typeof globalThis.",
  data: "Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers.",
  streams: "WHATWG stream primitives.",
  net: "Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging.",
  storage: "Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks.",
  dom: "Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT.",
  html: "HTML element constructors and related HTML collections/factories.",
  css: "CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights.",
  svg: "SVG element constructors and SVG value/list helper objects.",
  canvas: "2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics.",
  webgl: "WebGL rendering contexts and WebGL resource/event constructors.",
  webgpu: "WebGPU objects, enums, errors, resources, pipelines, queues, textures, and WGSL features.",
  audio: "Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers.",
  media: "Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis.",
  rtc: "WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors.",
  events: "Global event handler slots plus general event constructors and event listener methods.",
  input: "Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input.",
  animation: "Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF.",
  performance: "Performance timeline, observer, navigation/resource/paint/event timing, LCP.",
  scheduling: "Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting.",
  workers: "Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals.",
  security: "Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event.",
  devices: "Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint.",
  payment: "Payment Request API globals.",
  ui: "Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals.",
  observers: "Observer APIs: intersection, mutation, resize, reporting.",
  rest: "Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group.",
} as const satisfies Record<WindowGroupName, string>;

type Values<T> = T[keyof T];
type TupleItem<T> = T extends readonly (infer I)[] ? I : never;

export type GroupedWindowKey = TupleItem<Values<typeof windowGroups>>;
export type MissingWindowKey = Exclude<WindowKey, GroupedWindowKey>;
export type UnknownWindowKey = Exclude<GroupedWindowKey, WindowKey>;

// These fail compilation if the installed DOM/lib version has drifted.
type AssertNever<T extends never> = T;
type _AllWindowKeysAreGrouped = AssertNever<MissingWindowKey>;
type _NoUnknownWindowKeys = AssertNever<UnknownWindowKey>;

export const getWindowGroup = (key: WindowKey): WindowGroupName | undefined => {
  for (const group of Object.keys(windowGroups) as WindowGroupName[]) {
    if ((windowGroups[group] as readonly string[]).includes(key)) return group;
  }
  return undefined;
};
