/**
 * Generated grouping of keys on `window` from:
 *   keyof (Window & typeof globalThis)
 *
 * Source package used for extraction:
 *   @types/web@0.0.352
 *   typescript@6.0.3
 *
 * Master split:
 * - `direct`: developer-facing entrypoints: functions, singleton objects, static namespaces,
 *   and constructors developers commonly call intentionally.
 * - `indirect`: browser/environment-created classes and objects. This is the hide/noise bucket
 *   for IDE discovery. When classification was doubtful, the key was moved here.
 *
 * Classification rule applied after semantic grouping:
 * - `Event`, `Error`, and PascalCase names ending in `Event` or `Error` are indirect.
 * - `dispatchEvent` and `reportError` remain direct because they are callable methods/functions,
 *   not event/error classes.
 * - `rtc.direct` intentionally contains only `RTCPeerConnection`; the rest of RTC is indirect.
 * - HTML/SVG/WebGL constructor names are indirect: create them through document/canvas APIs.
 */

export type WindowKey = keyof (Window & typeof globalThis) & string;

export type WindowUsageKind = "direct" | "indirect";

export type WindowGroupName =
  | "deprecated"
  | "js"
  | "data"
  | "streams"
  | "net"
  | "storage"
  | "dom"
  | "html"
  | "css"
  | "svg"
  | "canvas"
  | "webgl"
  | "webgpu"
  | "audio"
  | "media"
  | "rtc"
  | "events"
  | "input"
  | "animation"
  | "performance"
  | "scheduling"
  | "workers"
  | "security"
  | "devices"
  | "payment"
  | "ui"
  | "observers"
  | "rest";

export const windowUsageGroups = {
  direct: {
    /** Deprecated or legacy browser globals. Direct entries are callable/readable but still not recommended. */
    deprecated: [
      "blur",
      "captureEvents",
      "clientInformation",
      "escape",
      "external",
      "orientation",
      "releaseEvents",
      "status",
      "unescape",
    ],
    /** ECMAScript language globals exposed through window/globalThis. */
    js: [
      "Array",
      "ArrayBuffer",
      "Atomics",
      "BigInt",
      "BigInt64Array",
      "BigUint64Array",
      "Boolean",
      "console",
      "DataView",
      "Date",
      "decodeURI",
      "decodeURIComponent",
      "encodeURI",
      "encodeURIComponent",
      "eval",
      "FinalizationRegistry",
      "Float32Array",
      "Float64Array",
      "Function",
      "globalThis",
      "Infinity",
      "Int16Array",
      "Int32Array",
      "Int8Array",
      "Intl",
      "isFinite",
      "isNaN",
      "JSON",
      "Map",
      "Math",
      "NaN",
      "Number",
      "Object",
      "parseFloat",
      "parseInt",
      "Promise",
      "Proxy",
      "Reflect",
      "RegExp",
      "Set",
      "SharedArrayBuffer",
      "String",
      "Symbol",
      "Uint16Array",
      "Uint32Array",
      "Uint8Array",
      "Uint8ClampedArray",
      "undefined",
      "WeakMap",
      "WeakRef",
      "WeakSet",
      "WebAssembly",
    ],
    /** Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers. */
    data: [
      "atob",
      "Blob",
      "btoa",
      "ByteLengthQueuingStrategy",
      "CompressionStream",
      "CountQueuingStrategy",
      "createImageBitmap",
      "DecompressionStream",
      "File",
      "FileReader",
      "FormData",
      "ImageData",
      "structuredClone",
      "TextDecoder",
      "TextDecoderStream",
      "TextEncoder",
      "TextEncoderStream",
      "URL",
      "URLPattern",
      "URLSearchParams",
    ],
    /** WHATWG stream primitives. */
    streams: ["ReadableStream", "TransformStream", "WritableStream"],
    /** Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging. */
    net: [
      "BroadcastChannel",
      "EventSource",
      "fetch",
      "Headers",
      "MessageChannel",
      "origin",
      "postMessage",
      "Request",
      "Response",
      "WebSocket",
      "WebTransport",
      "XMLHttpRequest",
    ],
    /** Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks. */
    storage: ["caches", "cookieStore", "IDBKeyRange", "indexedDB", "localStorage", "sessionStorage"],
    /** Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT. */
    dom: [
      "Comment",
      "customElements",
      "document",
      "Document",
      "DocumentFragment",
      "DOMMatrix",
      "DOMMatrixReadOnly",
      "DOMParser",
      "DOMPoint",
      "DOMPointReadOnly",
      "DOMQuad",
      "DOMRect",
      "DOMRectReadOnly",
      "Image",
      "NodeFilter",
      "Option",
      "Range",
      "Sanitizer",
      "StaticRange",
      "Text",
      "XMLSerializer",
      "XPathEvaluator",
      "XSLTProcessor",
    ],
    /** HTML element constructors and related HTML collections/factories. */
    html: [],
    /** CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights. */
    css: [
      "CSS",
      "CSSKeywordValue",
      "CSSMathClamp",
      "CSSMathInvert",
      "CSSMathMax",
      "CSSMathMin",
      "CSSMathNegate",
      "CSSMathProduct",
      "CSSMathSum",
      "CSSMatrixComponent",
      "CSSNumericValue",
      "CSSPerspective",
      "CSSRotate",
      "CSSScale",
      "CSSSkew",
      "CSSSkewX",
      "CSSSkewY",
      "CSSStyleSheet",
      "CSSStyleValue",
      "CSSTransformComponent",
      "CSSTransformValue",
      "CSSTranslate",
      "CSSUnitValue",
      "CSSUnparsedValue",
      "CSSVariableReferenceValue",
      "FontFace",
      "getComputedStyle",
      "Highlight",
      "matchMedia",
    ],
    /** SVG element constructors and SVG value/list helper objects. */
    svg: [],
    /** 2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics. */
    canvas: ["OffscreenCanvas", "Path2D"],
    /** WebGL rendering contexts and WebGL resource/event constructors. */
    webgl: [],
    /** WebGPU objects, constants, errors, resources, pipelines, queues, textures, and WGSL features. */
    webgpu: ["GPUBufferUsage", "GPUColorWrite", "GPUMapMode", "GPUShaderStage", "GPUTextureUsage"],
    /** Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers. */
    audio: [
      "AnalyserNode",
      "Audio",
      "AudioBuffer",
      "AudioBufferSourceNode",
      "AudioContext",
      "AudioWorkletNode",
      "BiquadFilterNode",
      "ChannelMergerNode",
      "ChannelSplitterNode",
      "ConstantSourceNode",
      "ConvolverNode",
      "DelayNode",
      "DynamicsCompressorNode",
      "GainNode",
      "IIRFilterNode",
      "MediaElementAudioSourceNode",
      "MediaStreamAudioDestinationNode",
      "MediaStreamAudioSourceNode",
      "OfflineAudioContext",
      "OscillatorNode",
      "PannerNode",
      "PeriodicWave",
      "StereoPannerNode",
      "WaveShaperNode",
    ],
    /** Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis. */
    media: [
      "AudioData",
      "AudioDecoder",
      "AudioEncoder",
      "documentPictureInPicture",
      "EncodedAudioChunk",
      "EncodedVideoChunk",
      "ImageCapture",
      "ImageDecoder",
      "MediaMetadata",
      "MediaRecorder",
      "MediaSource",
      "MediaStream",
      "speechSynthesis",
      "SpeechSynthesisUtterance",
      "VideoColorSpace",
      "VideoDecoder",
      "VideoEncoder",
      "VideoFrame",
      "VTTCue",
      "VTTRegion",
    ],
    /** WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors. */
    rtc: ["RTCPeerConnection"],
    /** Global event handler slots plus general event constructors and event listener methods. */
    events: ["addEventListener", "dispatchEvent", "EventTarget", "removeEventListener"],
    /** Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input. */
    input: ["ClipboardItem", "DataTransfer", "getSelection"],
    /** Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF. */
    animation: [
      "Animation",
      "cancelAnimationFrame",
      "DocumentTimeline",
      "KeyframeEffect",
      "requestAnimationFrame",
      "ScrollTimeline",
      "ViewTimeline",
    ],
    /** Performance timeline, observer, navigation/resource/paint/event timing, LCP. */
    performance: ["performance", "PerformanceObserver"],
    /** Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting. */
    scheduling: [
      "cancelIdleCallback",
      "clearInterval",
      "clearTimeout",
      "queueMicrotask",
      "reportError",
      "requestIdleCallback",
      "scheduler",
      "setInterval",
      "setTimeout",
      "TaskController",
    ],
    /** Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals. */
    workers: ["Notification", "SharedWorker", "Worker"],
    /** Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event. */
    security: [
      "AbortController",
      "AbortSignal",
      "crossOriginIsolated",
      "crypto",
      "isSecureContext",
      "originAgentCluster",
      "PublicKeyCredential",
    ],
    /** Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint. */
    devices: ["navigator"],
    /** Payment Request API globals. */
    payment: ["PaymentRequest"],
    /** Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals. */
    ui: [
      "alert",
      "close",
      "closed",
      "CloseWatcher",
      "confirm",
      "devicePixelRatio",
      "focus",
      "frameElement",
      "frames",
      "history",
      "innerHeight",
      "innerWidth",
      "length",
      "location",
      "locationbar",
      "menubar",
      "moveBy",
      "moveTo",
      "name",
      "navigation",
      "open",
      "opener",
      "outerHeight",
      "outerWidth",
      "pageXOffset",
      "pageYOffset",
      "parent",
      "personalbar",
      "print",
      "prompt",
      "resizeBy",
      "resizeTo",
      "screen",
      "screenLeft",
      "screenTop",
      "screenX",
      "screenY",
      "scroll",
      "scrollbars",
      "scrollBy",
      "scrollTo",
      "scrollX",
      "scrollY",
      "self",
      "statusbar",
      "stop",
      "toolbar",
      "top",
      "toString",
      "visualViewport",
      "window",
    ],
    /** Observer APIs: intersection, mutation, resize, reporting. */
    observers: ["IntersectionObserver", "MutationObserver", "ReportingObserver", "ResizeObserver"],
    /** Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group. */
    rest: [],
  },
  indirect: {
    /** Deprecated or legacy browser globals. Direct entries are callable/readable but still not recommended. */
    deprecated: [
      "AudioProcessingEvent",
      "event",
      "External",
      "HTMLDirectoryElement",
      "HTMLFontElement",
      "HTMLFrameElement",
      "HTMLFrameSetElement",
      "HTMLMarqueeElement",
      "HTMLParamElement",
      "MimeType",
      "MimeTypeArray",
      "onkeypress",
      "onorientationchange",
      "onunload",
      "onwebkitanimationend",
      "onwebkitanimationiteration",
      "onwebkitanimationstart",
      "onwebkittransitionend",
      "PerformanceNavigation",
      "PerformanceTiming",
      "Plugin",
      "PluginArray",
      "ScriptProcessorNode",
      "TextEvent",
    ],
    /** ECMAScript language globals exposed through window/globalThis. */
    js: [
      "AggregateError",
      "Error",
      "EvalError",
      "RangeError",
      "ReferenceError",
      "SyntaxError",
      "TypeError",
      "URIError",
    ],
    /** Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers. */
    data: ["BlobEvent", "DOMStringList", "DOMStringMap", "FileList", "FormDataEvent", "ImageBitmap"],
    /** WHATWG stream primitives. */
    streams: [
      "ReadableByteStreamController",
      "ReadableStreamBYOBReader",
      "ReadableStreamBYOBRequest",
      "ReadableStreamDefaultController",
      "ReadableStreamDefaultReader",
      "TransformStreamDefaultController",
      "WritableStreamDefaultController",
      "WritableStreamDefaultWriter",
    ],
    /** Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging. */
    net: [
      "MessageEvent",
      "MessagePort",
      "Origin",
      "WebTransportBidirectionalStream",
      "WebTransportDatagramDuplexStream",
      "WebTransportError",
      "WebTransportReceiveStream",
      "WebTransportSendStream",
      "XMLHttpRequestEventTarget",
      "XMLHttpRequestUpload",
    ],
    /** Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks. */
    storage: [
      "Cache",
      "CacheStorage",
      "CookieChangeEvent",
      "CookieStore",
      "CookieStoreManager",
      "FileSystem",
      "FileSystemDirectoryEntry",
      "FileSystemDirectoryHandle",
      "FileSystemDirectoryReader",
      "FileSystemEntry",
      "FileSystemFileEntry",
      "FileSystemFileHandle",
      "FileSystemHandle",
      "FileSystemWritableFileStream",
      "IDBCursor",
      "IDBCursorWithValue",
      "IDBDatabase",
      "IDBFactory",
      "IDBIndex",
      "IDBObjectStore",
      "IDBOpenDBRequest",
      "IDBRequest",
      "IDBTransaction",
      "IDBVersionChangeEvent",
      "Lock",
      "LockManager",
      "Storage",
      "StorageEvent",
      "StorageManager",
    ],
    /** Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT. */
    dom: [
      "AbstractRange",
      "Attr",
      "CaretPosition",
      "CDATASection",
      "CharacterData",
      "CustomElementRegistry",
      "CustomStateSet",
      "DocumentType",
      "DOMException",
      "DOMImplementation",
      "DOMRectList",
      "DOMTokenList",
      "Element",
      "ElementInternals",
      "FragmentDirective",
      "MathMLElement",
      "NamedNodeMap",
      "Node",
      "NodeIterator",
      "NodeList",
      "ProcessingInstruction",
      "RadioNodeList",
      "Selection",
      "ShadowRoot",
      "TreeWalker",
      "ValidityState",
      "XMLDocument",
      "XPathExpression",
      "XPathResult",
    ],
    /** HTML element constructors and related HTML collections/factories. */
    html: [
      "HTMLAllCollection",
      "HTMLAnchorElement",
      "HTMLAreaElement",
      "HTMLAudioElement",
      "HTMLBaseElement",
      "HTMLBodyElement",
      "HTMLBRElement",
      "HTMLButtonElement",
      "HTMLCanvasElement",
      "HTMLCollection",
      "HTMLDataElement",
      "HTMLDataListElement",
      "HTMLDetailsElement",
      "HTMLDialogElement",
      "HTMLDivElement",
      "HTMLDListElement",
      "HTMLDocument",
      "HTMLElement",
      "HTMLEmbedElement",
      "HTMLFieldSetElement",
      "HTMLFormControlsCollection",
      "HTMLFormElement",
      "HTMLHeadElement",
      "HTMLHeadingElement",
      "HTMLHRElement",
      "HTMLHtmlElement",
      "HTMLIFrameElement",
      "HTMLImageElement",
      "HTMLInputElement",
      "HTMLLabelElement",
      "HTMLLegendElement",
      "HTMLLIElement",
      "HTMLLinkElement",
      "HTMLMapElement",
      "HTMLMediaElement",
      "HTMLMenuElement",
      "HTMLMetaElement",
      "HTMLMeterElement",
      "HTMLModElement",
      "HTMLObjectElement",
      "HTMLOListElement",
      "HTMLOptGroupElement",
      "HTMLOptionElement",
      "HTMLOptionsCollection",
      "HTMLOutputElement",
      "HTMLParagraphElement",
      "HTMLPictureElement",
      "HTMLPreElement",
      "HTMLProgressElement",
      "HTMLQuoteElement",
      "HTMLScriptElement",
      "HTMLSelectElement",
      "HTMLSlotElement",
      "HTMLSourceElement",
      "HTMLSpanElement",
      "HTMLStyleElement",
      "HTMLTableCaptionElement",
      "HTMLTableCellElement",
      "HTMLTableColElement",
      "HTMLTableElement",
      "HTMLTableRowElement",
      "HTMLTableSectionElement",
      "HTMLTemplateElement",
      "HTMLTextAreaElement",
      "HTMLTimeElement",
      "HTMLTitleElement",
      "HTMLTrackElement",
      "HTMLUListElement",
      "HTMLUnknownElement",
      "HTMLVideoElement",
    ],
    /** CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights. */
    css: [
      "CSSAnimation",
      "CSSConditionRule",
      "CSSContainerRule",
      "CSSCounterStyleRule",
      "CSSFontFaceDescriptors",
      "CSSFontFaceRule",
      "CSSFontFeatureValuesRule",
      "CSSFontPaletteValuesRule",
      "CSSGroupingRule",
      "CSSImageValue",
      "CSSImportRule",
      "CSSKeyframeRule",
      "CSSKeyframesRule",
      "CSSLayerBlockRule",
      "CSSLayerStatementRule",
      "CSSMathValue",
      "CSSMediaRule",
      "CSSNamespaceRule",
      "CSSNestedDeclarations",
      "CSSNumericArray",
      "CSSPageDescriptors",
      "CSSPageRule",
      "CSSPositionTryDescriptors",
      "CSSPositionTryRule",
      "CSSPropertyRule",
      "CSSRule",
      "CSSRuleList",
      "CSSScopeRule",
      "CSSStartingStyleRule",
      "CSSStyleDeclaration",
      "CSSStyleProperties",
      "CSSStyleRule",
      "CSSSupportsRule",
      "CSSTransition",
      "CSSViewTransitionRule",
      "FontFaceSet",
      "FontFaceSetLoadEvent",
      "HighlightRegistry",
      "MediaList",
      "MediaQueryList",
      "MediaQueryListEvent",
      "StylePropertyMap",
      "StylePropertyMapReadOnly",
      "StyleSheet",
      "StyleSheetList",
      "WebKitCSSMatrix",
    ],
    /** SVG element constructors and SVG value/list helper objects. */
    svg: [
      "SVGAElement",
      "SVGAngle",
      "SVGAnimatedAngle",
      "SVGAnimatedBoolean",
      "SVGAnimatedEnumeration",
      "SVGAnimatedInteger",
      "SVGAnimatedLength",
      "SVGAnimatedLengthList",
      "SVGAnimatedNumber",
      "SVGAnimatedNumberList",
      "SVGAnimatedPreserveAspectRatio",
      "SVGAnimatedRect",
      "SVGAnimatedString",
      "SVGAnimatedTransformList",
      "SVGAnimateElement",
      "SVGAnimateMotionElement",
      "SVGAnimateTransformElement",
      "SVGAnimationElement",
      "SVGCircleElement",
      "SVGClipPathElement",
      "SVGComponentTransferFunctionElement",
      "SVGDefsElement",
      "SVGDescElement",
      "SVGElement",
      "SVGEllipseElement",
      "SVGFEBlendElement",
      "SVGFEColorMatrixElement",
      "SVGFEComponentTransferElement",
      "SVGFECompositeElement",
      "SVGFEConvolveMatrixElement",
      "SVGFEDiffuseLightingElement",
      "SVGFEDisplacementMapElement",
      "SVGFEDistantLightElement",
      "SVGFEDropShadowElement",
      "SVGFEFloodElement",
      "SVGFEFuncAElement",
      "SVGFEFuncBElement",
      "SVGFEFuncGElement",
      "SVGFEFuncRElement",
      "SVGFEGaussianBlurElement",
      "SVGFEImageElement",
      "SVGFEMergeElement",
      "SVGFEMergeNodeElement",
      "SVGFEMorphologyElement",
      "SVGFEOffsetElement",
      "SVGFEPointLightElement",
      "SVGFESpecularLightingElement",
      "SVGFESpotLightElement",
      "SVGFETileElement",
      "SVGFETurbulenceElement",
      "SVGFilterElement",
      "SVGForeignObjectElement",
      "SVGGElement",
      "SVGGeometryElement",
      "SVGGradientElement",
      "SVGGraphicsElement",
      "SVGImageElement",
      "SVGLength",
      "SVGLengthList",
      "SVGLinearGradientElement",
      "SVGLineElement",
      "SVGMarkerElement",
      "SVGMaskElement",
      "SVGMatrix",
      "SVGMetadataElement",
      "SVGMPathElement",
      "SVGNumber",
      "SVGNumberList",
      "SVGPathElement",
      "SVGPatternElement",
      "SVGPoint",
      "SVGPointList",
      "SVGPolygonElement",
      "SVGPolylineElement",
      "SVGPreserveAspectRatio",
      "SVGRadialGradientElement",
      "SVGRect",
      "SVGRectElement",
      "SVGScriptElement",
      "SVGSetElement",
      "SVGStopElement",
      "SVGStringList",
      "SVGStyleElement",
      "SVGSVGElement",
      "SVGSwitchElement",
      "SVGSymbolElement",
      "SVGTextContentElement",
      "SVGTextElement",
      "SVGTextPathElement",
      "SVGTextPositioningElement",
      "SVGTitleElement",
      "SVGTransform",
      "SVGTransformList",
      "SVGTSpanElement",
      "SVGUnitTypes",
      "SVGUseElement",
      "SVGViewElement",
    ],
    /** 2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics. */
    canvas: [
      "CanvasCaptureMediaStreamTrack",
      "CanvasGradient",
      "CanvasPattern",
      "CanvasRenderingContext2D",
      "ImageBitmapRenderingContext",
      "OffscreenCanvasRenderingContext2D",
      "TextMetrics",
    ],
    /** WebGL rendering contexts and WebGL resource/event constructors. */
    webgl: [
      "WebGL2RenderingContext",
      "WebGLActiveInfo",
      "WebGLBuffer",
      "WebGLContextEvent",
      "WebGLFramebuffer",
      "WebGLProgram",
      "WebGLQuery",
      "WebGLRenderbuffer",
      "WebGLRenderingContext",
      "WebGLSampler",
      "WebGLShader",
      "WebGLShaderPrecisionFormat",
      "WebGLSync",
      "WebGLTexture",
      "WebGLTransformFeedback",
      "WebGLUniformLocation",
      "WebGLVertexArrayObject",
    ],
    /** WebGPU objects, constants, errors, resources, pipelines, queues, textures, and WGSL features. */
    webgpu: [
      "GPU",
      "GPUAdapter",
      "GPUAdapterInfo",
      "GPUBindGroup",
      "GPUBindGroupLayout",
      "GPUBuffer",
      "GPUCanvasContext",
      "GPUCommandBuffer",
      "GPUCommandEncoder",
      "GPUCompilationInfo",
      "GPUCompilationMessage",
      "GPUComputePassEncoder",
      "GPUComputePipeline",
      "GPUDevice",
      "GPUDeviceLostInfo",
      "GPUError",
      "GPUExternalTexture",
      "GPUInternalError",
      "GPUOutOfMemoryError",
      "GPUPipelineError",
      "GPUPipelineLayout",
      "GPUQuerySet",
      "GPUQueue",
      "GPURenderBundle",
      "GPURenderBundleEncoder",
      "GPURenderPassEncoder",
      "GPURenderPipeline",
      "GPUSampler",
      "GPUShaderModule",
      "GPUSupportedFeatures",
      "GPUSupportedLimits",
      "GPUTexture",
      "GPUTextureView",
      "GPUUncapturedErrorEvent",
      "GPUValidationError",
      "WGSLLanguageFeatures",
    ],
    /** Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers. */
    audio: [
      "AudioDestinationNode",
      "AudioListener",
      "AudioNode",
      "AudioParam",
      "AudioParamMap",
      "AudioScheduledSourceNode",
      "AudioWorklet",
      "BaseAudioContext",
      "OfflineAudioCompletionEvent",
    ],
    /** Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis. */
    media: [
      "DocumentPictureInPicture",
      "DocumentPictureInPictureEvent",
      "ImageTrack",
      "ImageTrackList",
      "MediaCapabilities",
      "MediaDeviceInfo",
      "MediaDevices",
      "MediaEncryptedEvent",
      "MediaError",
      "MediaKeyMessageEvent",
      "MediaKeys",
      "MediaKeySession",
      "MediaKeyStatusMap",
      "MediaKeySystemAccess",
      "MediaSession",
      "MediaSourceHandle",
      "MediaStreamTrack",
      "MediaStreamTrackEvent",
      "OverconstrainedError",
      "PictureInPictureEvent",
      "PictureInPictureWindow",
      "RemotePlayback",
      "SourceBuffer",
      "SourceBufferList",
      "SpeechSynthesis",
      "SpeechSynthesisErrorEvent",
      "SpeechSynthesisEvent",
      "SpeechSynthesisVoice",
      "TextTrack",
      "TextTrackCue",
      "TextTrackCueList",
      "TextTrackList",
      "TimeRanges",
      "TrackEvent",
      "VideoPlaybackQuality",
    ],
    /** WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors. */
    rtc: [
      "RTCCertificate",
      "RTCDataChannel",
      "RTCDataChannelEvent",
      "RTCDtlsTransport",
      "RTCDTMFSender",
      "RTCDTMFToneChangeEvent",
      "RTCEncodedAudioFrame",
      "RTCEncodedVideoFrame",
      "RTCError",
      "RTCErrorEvent",
      "RTCIceCandidate",
      "RTCIceTransport",
      "RTCPeerConnectionIceErrorEvent",
      "RTCPeerConnectionIceEvent",
      "RTCRtpReceiver",
      "RTCRtpScriptTransform",
      "RTCRtpSender",
      "RTCRtpTransceiver",
      "RTCSctpTransport",
      "RTCSessionDescription",
      "RTCStatsReport",
      "RTCTrackEvent",
    ],
    /** Global event handler slots plus general event constructors and event listener methods. */
    events: [
      "AnimationEvent",
      "AnimationPlaybackEvent",
      "BeforeUnloadEvent",
      "CloseEvent",
      "CommandEvent",
      "ContentVisibilityAutoStateChangeEvent",
      "CustomEvent",
      "DeviceMotionEvent",
      "DeviceOrientationEvent",
      "ErrorEvent",
      "Event",
      "EventCounts",
      "GamepadEvent",
      "HashChangeEvent",
      "MIDIConnectionEvent",
      "MIDIMessageEvent",
      "onabort",
      "onafterprint",
      "onanimationcancel",
      "onanimationend",
      "onanimationiteration",
      "onanimationstart",
      "onauxclick",
      "onbeforeinput",
      "onbeforematch",
      "onbeforeprint",
      "onbeforetoggle",
      "onbeforeunload",
      "onblur",
      "oncancel",
      "oncanplay",
      "oncanplaythrough",
      "onchange",
      "onclick",
      "onclose",
      "oncommand",
      "oncontextlost",
      "oncontextmenu",
      "oncontextrestored",
      "oncopy",
      "oncuechange",
      "oncut",
      "ondblclick",
      "ondevicemotion",
      "ondeviceorientation",
      "ondeviceorientationabsolute",
      "ondrag",
      "ondragend",
      "ondragenter",
      "ondragleave",
      "ondragover",
      "ondragstart",
      "ondrop",
      "ondurationchange",
      "onemptied",
      "onended",
      "onerror",
      "onfocus",
      "onformdata",
      "ongamepadconnected",
      "ongamepaddisconnected",
      "ongotpointercapture",
      "onhashchange",
      "oninput",
      "oninvalid",
      "onkeydown",
      "onkeyup",
      "onlanguagechange",
      "onload",
      "onloadeddata",
      "onloadedmetadata",
      "onloadstart",
      "onlostpointercapture",
      "onmessage",
      "onmessageerror",
      "onmousedown",
      "onmouseenter",
      "onmouseleave",
      "onmousemove",
      "onmouseout",
      "onmouseover",
      "onmouseup",
      "onoffline",
      "ononline",
      "onpagehide",
      "onpagereveal",
      "onpageshow",
      "onpageswap",
      "onpaste",
      "onpause",
      "onplay",
      "onplaying",
      "onpointercancel",
      "onpointerdown",
      "onpointerenter",
      "onpointerleave",
      "onpointermove",
      "onpointerout",
      "onpointerover",
      "onpointerrawupdate",
      "onpointerup",
      "onpopstate",
      "onprogress",
      "onratechange",
      "onrejectionhandled",
      "onreset",
      "onresize",
      "onscroll",
      "onscrollend",
      "onsecuritypolicyviolation",
      "onseeked",
      "onseeking",
      "onselect",
      "onselectionchange",
      "onselectstart",
      "onslotchange",
      "onstalled",
      "onstorage",
      "onsubmit",
      "onsuspend",
      "ontimeupdate",
      "ontoggle",
      "ontouchcancel",
      "ontouchend",
      "ontouchmove",
      "ontouchstart",
      "ontransitioncancel",
      "ontransitionend",
      "ontransitionrun",
      "ontransitionstart",
      "onunhandledrejection",
      "onvolumechange",
      "onwaiting",
      "onwheel",
      "PageRevealEvent",
      "PageSwapEvent",
      "PageTransitionEvent",
      "PopStateEvent",
      "ProgressEvent",
      "PromiseRejectionEvent",
      "SubmitEvent",
      "ToggleEvent",
      "TransitionEvent",
      "UIEvent",
    ],
    /** Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input. */
    input: [
      "Clipboard",
      "ClipboardEvent",
      "CompositionEvent",
      "DataTransferItem",
      "DataTransferItemList",
      "DragEvent",
      "FocusEvent",
      "Gamepad",
      "GamepadButton",
      "GamepadHapticActuator",
      "InputDeviceInfo",
      "InputEvent",
      "KeyboardEvent",
      "MouseEvent",
      "PointerEvent",
      "Touch",
      "TouchEvent",
      "TouchList",
      "WheelEvent",
    ],
    /** Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF. */
    animation: ["AnimationEffect", "AnimationTimeline", "ViewTransition", "ViewTransitionTypeSet"],
    /** Performance timeline, observer, navigation/resource/paint/event timing, LCP. */
    performance: [
      "LargestContentfulPaint",
      "Performance",
      "PerformanceEntry",
      "PerformanceEventTiming",
      "PerformanceMark",
      "PerformanceMeasure",
      "PerformanceNavigationTiming",
      "PerformanceObserverEntryList",
      "PerformancePaintTiming",
      "PerformanceResourceTiming",
      "PerformanceServerTiming",
    ],
    /** Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting. */
    scheduling: ["IdleDeadline", "Scheduler", "TaskPriorityChangeEvent", "TaskSignal"],
    /** Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals. */
    workers: [
      "PushManager",
      "PushSubscription",
      "PushSubscriptionOptions",
      "ServiceWorker",
      "ServiceWorkerContainer",
      "ServiceWorkerRegistration",
      "Worklet",
    ],
    /** Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event. */
    security: [
      "AuthenticatorAssertionResponse",
      "AuthenticatorAttestationResponse",
      "AuthenticatorResponse",
      "Credential",
      "CredentialsContainer",
      "Crypto",
      "CryptoKey",
      "DigitalCredential",
      "Permissions",
      "PermissionStatus",
      "SecurityPolicyViolationEvent",
      "SubtleCrypto",
    ],
    /** Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint. */
    devices: [
      "Geolocation",
      "GeolocationCoordinates",
      "GeolocationPosition",
      "GeolocationPositionError",
      "MIDIAccess",
      "MIDIInput",
      "MIDIInputMap",
      "MIDIOutput",
      "MIDIOutputMap",
      "MIDIPort",
      "Navigator",
      "NavigatorLogin",
      "Serial",
      "SerialPort",
      "UserActivation",
      "WakeLock",
      "WakeLockSentinel",
    ],
    /** Payment Request API globals. */
    payment: ["PaymentAddress", "PaymentMethodChangeEvent", "PaymentRequestUpdateEvent", "PaymentResponse"],
    /** Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals. */
    ui: [
      "BarProp",
      "History",
      "Location",
      "NavigateEvent",
      "Navigation",
      "NavigationActivation",
      "NavigationCurrentEntryChangeEvent",
      "NavigationDestination",
      "NavigationHistoryEntry",
      "NavigationPrecommitController",
      "NavigationPreloadManager",
      "NavigationTransition",
      "Screen",
      "ScreenOrientation",
      "VisualViewport",
      "Window",
    ],
    /** Observer APIs: intersection, mutation, resize, reporting. */
    observers: ["IntersectionObserverEntry", "MutationRecord", "ResizeObserverEntry", "ResizeObserverSize"],
    /** Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group. */
    rest: [
      "SpeechRecognitionAlternative",
      "SpeechRecognitionErrorEvent",
      "SpeechRecognitionEvent",
      "SpeechRecognitionResult",
      "SpeechRecognitionResultList",
      "webkitURL",
    ],
  },
} as const satisfies Record<WindowUsageKind, Record<WindowGroupName, readonly WindowKey[]>>;

export const directWindowGroups = windowUsageGroups.direct;
export const indirectWindowGroups = windowUsageGroups.indirect;

export const windowGroupDescriptions = {
  deprecated: "Deprecated or legacy browser globals. Direct entries are callable/readable but still not recommended.",
  js: "ECMAScript language globals exposed through window/globalThis.",
  data: "Binary/text data, files, URLs, encoding, structured clone, and image bitmap helpers.",
  streams: "WHATWG stream primitives.",
  net: "Network, messaging, HTTP/fetch, WebSocket, WebTransport, XHR, EventSource, and origin messaging.",
  storage: "Storage APIs: local/session storage, IndexedDB, Cache API, cookies, file-system handles, locks.",
  dom: "Core DOM tree, ranges, parsing/serialization, selection, custom elements, geometry, XPath/XSLT.",
  html: "HTML element constructors and related HTML collections/factories.",
  css: "CSSOM, constructable stylesheets, CSS Typed OM, media queries, font loading, highlights.",
  svg: "SVG element constructors and SVG value/list helper objects.",
  canvas: "2D canvas, offscreen canvas, bitmap rendering, paths, and canvas metrics.",
  webgl: "WebGL rendering contexts and WebGL resource/event constructors.",
  webgpu: "WebGPU objects, constants, errors, resources, pipelines, queues, textures, and WGSL features.",
  audio: "Web Audio graph, AudioContext, audio nodes, params, worklets, and audio processing helpers.",
  media: "Media capture/playback, WebCodecs, EME, MediaSource, PiP, text tracks, speech synthesis.",
  rtc: "WebRTC transport, peer connection, tracks, RTP, SCTP, ICE, encoded frames, and RTC errors.",
  events: "Global event handler slots plus general event constructors and event listener methods.",
  input: "Clipboard, drag/drop, keyboard, mouse, pointer, touch, focus, gamepad, composition, selection input.",
  animation: "Web Animations API, CSS animation/transition globals, timelines, view transitions, RAF.",
  performance: "Performance timeline, observer, navigation/resource/paint/event timing, LCP.",
  scheduling: "Timers, idle callbacks, microtasks, scheduler/task primitives, and global error reporting.",
  workers: "Worker, SharedWorker, Service Worker, Worklet, Push, and Notification globals.",
  security: "Crypto, credentials, WebAuthn, permissions, secure-context and isolation flags, CSP event.",
  devices: "Navigator-side hardware/location/device APIs: geolocation, MIDI, serial, wake lock, GPU entrypoint.",
  payment: "Payment Request API globals.",
  ui: "Window/frame/navigation/screen/dialog/scroll/resize/focus/location/history/browser-chrome globals.",
  observers: "Observer APIs: intersection, mutation, resize, reporting.",
  rest: "Rare, vendor-prefixed, or niche globals that do not justify a larger top-level group.",
} as const satisfies Record<WindowGroupName, string>;

export const windowUsageCounts = {
  direct: {
    deprecated: 9,
    js: 52,
    data: 20,
    streams: 3,
    net: 12,
    storage: 6,
    dom: 23,
    html: 0,
    css: 29,
    svg: 0,
    canvas: 2,
    webgl: 0,
    webgpu: 5,
    audio: 24,
    media: 20,
    rtc: 1,
    events: 4,
    input: 3,
    animation: 7,
    performance: 2,
    scheduling: 10,
    workers: 3,
    security: 7,
    devices: 1,
    payment: 1,
    ui: 51,
    observers: 4,
    rest: 0,
  },
  indirect: {
    deprecated: 24,
    js: 8,
    data: 6,
    streams: 8,
    net: 10,
    storage: 29,
    dom: 29,
    html: 70,
    css: 46,
    svg: 97,
    canvas: 7,
    webgl: 17,
    webgpu: 36,
    audio: 9,
    media: 35,
    rtc: 22,
    events: 144,
    input: 19,
    animation: 4,
    performance: 11,
    scheduling: 4,
    workers: 7,
    security: 12,
    devices: 17,
    payment: 4,
    ui: 16,
    observers: 4,
    rest: 6,
  },
  total: {
    direct: 299,
    indirect: 701,
    all: 1000,
  },
} as const;

type Values<T> = T[keyof T];
type TupleItem<T> = T extends readonly (infer I)[] ? I : never;

export type DirectWindowKey = TupleItem<Values<typeof directWindowGroups>>;
export type IndirectWindowKey = TupleItem<Values<typeof indirectWindowGroups>>;
export type GroupedWindowKey = DirectWindowKey | IndirectWindowKey;

export type MissingWindowKey = Exclude<WindowKey, GroupedWindowKey>;
export type UnknownWindowKey = Exclude<GroupedWindowKey, WindowKey>;
export type OverlappedWindowKey = Extract<DirectWindowKey, IndirectWindowKey>;

// These fail compilation if the installed DOM/lib version has drifted or the split is wrong.
type AssertNever<T extends never> = T;
type _AllWindowKeysAreGrouped = AssertNever<MissingWindowKey>;
type _NoUnknownWindowKeys = AssertNever<UnknownWindowKey>;
type _NoDirectIndirectOverlap = AssertNever<OverlappedWindowKey>;

export const getWindowUsageKind = (key: WindowKey): WindowUsageKind | undefined => {
  for (const usage of Object.keys(windowUsageGroups) as WindowUsageKind[]) {
    const groups = windowUsageGroups[usage];
    for (const group of Object.keys(groups) as WindowGroupName[]) {
      if ((groups[group] as readonly string[]).includes(key)) return usage;
    }
  }
  return undefined;
};

export const getWindowGroupName = (key: WindowKey): WindowGroupName | undefined => {
  for (const usage of Object.keys(windowUsageGroups) as WindowUsageKind[]) {
    const groups = windowUsageGroups[usage];
    for (const group of Object.keys(groups) as WindowGroupName[]) {
      if ((groups[group] as readonly string[]).includes(key)) return group;
    }
  }
  return undefined;
};
